from patch.api import *

def build():
    write_head("7.38c", "27.03.2025")

    W(section("General Updates"))
    
    W(plain_header("Dire Safe Lane Jungle"))
    W(ul_open())
    W(li("The tree lines above and below the tower have been reworked", t("MISC")))
    W(li("The Dire Safe Lane hard camp has been moved away from the Dire Safe Lane Tier 1 tower, and had its tree line reduced and rotated to face the river", t("NERF")))
    W(li("The Dire Safe Lane Tier 1 tower has been moved forward, away from the Dire base and closer to where the creeps initially meet", t("MISC")))
    W(li("The Top Lane creep paths have been slightly adjusted so the creeps meet closer to the Dire tower", t("MISC")))
    W(li("The cliff above the Dire Safe Lane small camp has been extended slightly towards the Dire Safe Lane Tier 1 tower, and the small camp has been moved and had its tree line adjusted", t("MISC")))
    W(li("The ramp leading to the river and the Roshan Pit from the Dire Safe Lane pull area has been moved towards the Pit slightly", t("MISC")))
    W(li("Several additional tree and visual adjustments have been made to this area", t("MISC")))
    W(ul_close())
    
    W(plain_header("Top Roshan Pit"))
    W(ul_open())
    W(li("Fixed a spot at the north side of the pit that had incorrect vision rules", t("MISC")))
    W(li("Fixed some areas that visually looked pathable but were not", t("MISC")))
    W(ul_close())
    
    W(plain_header("Bottom Lane"))
    W(ul_open())
    W(li("A tree near the Radiant Safe Lane hard camp has been removed", t("DEL")))
    W(li("Several trees have been removed from the Radiant high ground leading to the Bottom Roshan Pit", t("DEL")))
    W(li("Trees have been added around the Dire Bottom Tier 1 tower, and several tree positions adjusted", t("MISC")))
    W(li("The Watcher above the secret shop has been repositioned between the ramps from Dire Mid Tier 1 and the bottom Roshan Pit", t("MISC")))
    W(li("Fixed unnecessary pathing blockers at the left of the entrance to the Dire Base through the team only gate", t("MISC")))
    W(li("Several additional tree and visual adjustments have been made to this area", t("MISC")))
    W(ul_close())
    
    # ===== ITEM UPDATES =====
    W(section("Item Updates"))
    W(item_header("Desolator"))
    W(ul_open())
    W(li("Damage bonus increased from +50 to +55", b(50, 55)))
    W(ul_close())
    W(item_header("Helm of the Dominator"))
    W(ul_open())
    W(li("Dominated creep is now considered a creep-hero", t("NEW"), extra=inline_note("It cannot be dominated, persuaded or enchanted, and it isn't instantly killed by Hand of Midas, Mirana's Sacred Arrow, etc.")))
    W(ul_close())
    W(item_header("Helm of the Overlord"))
    W(ul_open())
    W(li("Dominated creep is now considered a creep-hero", t("NEW"), extra=inline_note("It cannot be dominated, persuaded or enchanted, and it isn't instantly killed by Hand of Midas, Mirana's Sacred Arrow, etc.")))
    W(ul_close())
    W(item_header("Mage Slayer"))
    W(ul_open())
    W(li("Mage Slayer damage per second decreased from 25 to 20", b(25, 20)))
    W(ul_close())
    W(item_header("Orb of Corrosion"))
    W(ul_open())
    W(li("Corrosion armor reduction decreased from 3 to 2", b(3, 2)))
    W(ul_close())
    W(item_header("Revenant's Brooch"))
    W(ul_open())
    W(li("Spell Lifesteal bonus decreased from +16% to +14%", b(16, 14)))
    W(ul_close())
    W(item_header("Spirit Vessel"))
    W(ul_open())
    W(li("Soul Release healing, regen and lifesteal reduction increased from 60% to 70%", b(60, 70)))
    W(ul_close())
    
    # ===== NEUTRAL ITEM UPDATES =====
    W(section("Neutral Item Updates"))
    
    W(plain_header("Artifact changes", dynamics=False, sublabel=True))
    W(item_header("Mana Draught"))
    W(ul_open())
    W(li("Bottoms Up cooldown increased from 40s to 60s", b(40, 60, l=True)))
    W(ul_close())
    W(item_header("Orb of Destruction"))
    W(ul_open())
    W(li("Impeding Corruption Slow (Melee) decreased from 10% to 8%", b(10, 8)))
    W(li("Impeding Corruption Slow (Range) decreased from 5% to 4%", b(5, 4)))
    W(ul_close())
    W(item_header("Pollywog Charm"))
    W(ul_open())
    W(li("Ribbit mana cost decreased from 40 to 0", b(40, 0, l=True)))
    W(ul_close())
    W(item_header("Ripper's Lash"))
    W(ul_open())
    W(li("Flay Bonus Damage (Heroes) increased from 12 to 16", b(12, 16)))
    W(ul_close())
    W(item_header("Searing Signet"))
    W(ul_open())
    W(li("Burn Through duration increased from 5s to 6s", b(5, 6)))
    W(li("Burn Through total damage decreased from 75 to 72", b(75, 72), extra=inline_note("Damage per second decreased from 15 to 12 — " + b(15, 12))))
    W(li("Burn Through damage is now classified as Health Removal", t("REWORK"), extra=inline_note("It no longer will trigger on hit effects or cancel Blink Daggers")))
    W(ul_close())
    W(item_header("Nemesis Curse"))
    W(ul_open())
    W(li("Glass Cannon self damage amp decreased from 8% to 6%", b(8, 6, l=True)))
    W(ul_close())
    W(item_header("Crippling Crossbow"))
    W(ul_open())
    W(li("Hobble mana cost decreased from 75 to 50", b(75, 50, l=True)))
    W(ul_close())
    W(item_header("Mind Breaker"))
    W(ul_open())
    W(li("Silence Strike cooldown increased from 12s to 16s", b(12, 16, l=True)))
    W(ul_close())
    W(item_header("Pirate Hat"))
    W(ul_open())
    W(li("Plunder steal radius increased from 1200 to 2400", b(1200, 2400)))
    W(ul_close())
    W(item_header("Unrelenting Eye"))
    W(ul_open())
    W(li("Relentless enemy search radius increased from 300 to 600", b(300, 600, l=True)))
    W(ul_close())
    
    W(plain_header("Enchantment changes", dynamics=False, sublabel=True))
    W(enchant_header("Alert"))
    W(ul_open())
    W(li("Attack Speed bonus increased from +10/15/20/25 to +10/17/24/35", b([10, 15, 20, 25], [10, 17, 24, 35])))
    W(ul_close())
    W(enchant_header("Mystical"))
    W(ul_open())
    W(li("Mana Regen bonus decreased from +1/2/3/4 to +1/1.75/2.5/3.25", b([1, 2, 3, 4], [1, 1.75, 2.5, 3.25])))
    W(ul_close())
    W(enchant_header("Tough"))
    W(ul_open())
    W(li("Damage bonus increased from +5/8/11/14 to +7/10/13/17", b([5, 8, 11, 14], [7, 10, 13, 17])))
    W(ul_close())
    W(enchant_header("Keen-eyed"))
    W(ul_open())
    W(li("Max Mana reduction decreased from 15% to 10%", b(15, 10, l=True)))
    W(ul_close())
    W(enchant_header("Vast"))
    W(ul_open())
    W(li("Attack Range bonus increased from +60/90 to +75/110", b([60, 90], [75, 110])))
    W(ul_close())
    W(enchant_header("Crude"))
    W(ul_open())
    W(li("Intelligence reduction decreased from 15% to 8%", b(15, 8, l=True)))
    W(ul_close())
    W(enchant_header("Timeless"))
    W(ul_open())
    W(li("Spell Amplification bonus decreased from +10/20% to +8/16%", b([10, 20], [8, 16])))
    W(ul_close())
    W(enchant_header("Titanic"))
    W(ul_open())
    W(li("Base Attack Damage bonus decreased from +15/25% to +10/20%", b([15, 25], [10, 20])))
    W(ul_close())
    W(enchant_header("Feverish"))
    W(ul_open())
    W(li("Mana Cost/Mana Loss Increase decreased from +10% to +7%", b(10, 7, l=True)))
    W(ul_close())
    W(enchant_header("Wise"))
    W(ul_open())
    W(li("Experience per Minute bonus increased from +600 to +1000", b(600, 1000)))
    W(ul_close())
    
    # ===== HERO UPDATES =====
    W(section("Hero Updates"))
    
    # Abaddon
    W(hero_header("Abaddon"))
    W(ul_open())
    W(li("Base Armor decreased by 1", t("NERF"), extra=note_box(hero="Abaddon", field="ArmorPhysical", before_patch="7.38b")))
    W(ul_close())
    W(facet_header("abaddon_mephitic_shroud"))
    W(ul_open())
    W(li("Aphotic Shield: Cooldown increased from 14/12/10/8s to 15/13/11/9s", b([14, 12, 10, 8], [15, 13, 11, 9], l=True)))
    W(ul_close())
    W(ability("Curse of Avernus", slug="abaddon_frostmourne"))
    W(ul_open())
    W(li("No longer deals damage to buildings", t("DEL")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Curse of Avernus DPS decreased from +50 to +40", b(50, 40)))
    W(li("Level 25 Talent Curse of Avernus Attack Speed Bonus decreased from +80 to +65", b(80, 65)))
    W(ul_close())
    
    # Alchemist
    W(hero_header("Alchemist"))
    W(ability("Corrosive Weaponry", slug="alchemist_corrosive_weaponry"))
    W(ul_open())
    W(li("Unstable Concoction stack count per second of brew time now rounds up to the nearest second (minimum 1 stack)", t("MISC")))
    W(ul_close())
    
    # Ancient Apparition
    W(hero_header("Ancient Apparition"))
    W(ability("Ice Vortex", slug="ancient_apparition_ice_vortex"))
    W(ul_open())
    W(li("Mana Cost increased from 40/50/60/70 to 40/55/70/85", b([40, 50, 60, 70], [40, 55, 70, 85], l=True)))
    W(ul_close())
    W(ability("Chilling Touch", slug="ancient_apparition_chilling_touch"))
    W(ul_open())
    W(li("Attack Range Bonus decreased from 80/120/160/200 to 60/90/120/150", b([80, 120, 160, 200], [60, 90, 120, 150])))
    W(ul_close())
    
    # Batrider
    W(hero_header("Batrider"))
    W(ability("Firefly", slug="batrider_firefly"))
    W(ul_open())
    W(li("Radius increased from 200 to 250", b(200, 250)))
    W(ul_close())
    W(ability("Flaming Lasso", slug="batrider_flaming_lasso"))
    W(ul_open())
    W(li("Forced movement applied by Batrider's allies to the lassoed target from certain abilities no longer cancel lasso", t("MISC"),
        extra=inline_note("Dark Willow's Terrorize, Death Prophet's Spirit Siphon (Fear from Aghanim's Shard), Keeper of the Light's Will-o-Wisp, Lich's Sinister Gaze, Lone Druid's (and Spirit Bear's) Savage Roar, Muerta's Dead Shot, Pudge's Dismember, Ringmaster's Wheel of Wonder, Shadow Fiend's Requiem of Souls, Terrorblade's Terror Wave, Tinker's Defense Matrix (blink with Translocator facet), Tinker's Warp Flare (still applies damage, but does not move the target), Tusk's Walrus Kick (still applies damage, but does not move the target)")))
    W(li("The following abilities continue to break the lasso: Centaur Warrunner's Hitch a Ride, Chaos Knight's Reality Rift, Disruptor's Glimpse, Kunkka's X Marks the Spot, Magnus' Reverse Polarity, Mars' Arena of Blood (created by an ally) and Vengeful Spirit's Nether Swap", t("MISC")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent 2 Flamebreak Charges replaced with -6s Flamebreak Cooldown", t("REWORK")))
    W(li("Level 20 Talent Smoldering Resin Duration increased from +2s to +4s", b(2, 4)))
    W(li("Level 25 Talent Sticky Napalm Damage increased from +15 to +20", b(15, 20)))
    W(ul_close())
    
    # Brewmaster
    W(hero_header("Brewmaster"))
    W(ability("Primal Split", slug="brewmaster_primal_split"))
    W(ability("Earth Brewling", slug="brewmaster_earth_unit", icon_url="../icons/units/brewmaster_earth_unit.png"))
    W(ul_open())
    W(li("Debuff Immunity magic resistance increased from 50% to 80%", b(50, 80)))
    W(ul_close())
    W(ability("Void Brewling", slug="brewmaster_void_unit", icon_url="../icons/units/brewmaster_void_unit.png"))
    W(ul_open())
    W(li("Astral Pull Damage increased from 50/100/150 to 75/150/225", b([50, 100, 150], [75, 150, 225])))
    W(li("Astral Pull Distance increased from 300/500/700 to 450/575/700", b([300, 500, 700], [450, 575, 700])))
    W(ul_close())
    
    # Chen
    W(hero_header("Chen"))
    W(ability("Zealot", slug="chen_zealot", innate=True))
    W(ul_open())
    W(li("Summon Convert: Convert is now considered a creep-hero", t("NEW"), extra=inline_note("It cannot be dominated, persuaded or enchanted, and it isn't instantly killed by Hand of Midas, Mirana's Sacred Arrow, etc.")))
    W(ul_close())
    
    # Dark Seer
    W(hero_header("Dark Seer"))
    W(ul_open())
    W(li("Base Damage decreased by 2", bstat_h("Dark Seer", "AttackDamageMin", "7.38b", -2), extra=note_box(hero="Dark Seer", field="AttackDamageMin", before_patch="7.38b")))
    W(li("Damage at level 1 decreased from 54–60 to 52–58", br(54, 60, 52, 58)))
    W(ul_close())
    W(facet_header("dark_seer_movespd"))
    W(ul_open())
    W(li("Radius increased from 900 to 1200", b(900, 1200)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Wall of Replica Illusion Damage decreased from +20% to +15%", b(20, 15)))
    W(ul_close())
    
    # Dazzle
    W(hero_header("Dazzle"))
    W(ability("Shadow Wave", slug="dazzle_shadow_wave"))
    W(ul_open())
    W(li("No longer has increased healing and damage when bouncing on enemies with Aghanim's Scepter", t("DEL")))
    W(ul_close())
    W(ability("Nothl Projection", slug="dazzle_nothl_projection"))
    W(ul_open())
    W(li("Cast Range decreased from 600 to 450", b(600, 450)))
    W(li("Leash pull strength growth increased from 0.5 to 1.5", b(0.5, 1.5, l=True), extra=inline_note("This means for every 1 unit past 1600, the strength of the pull will increase by 1.5 unit/s instead of 0.5")))
    W(li("Max Duration decreased from 15s to 12s", b(15, 12)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent +90 Attack Speed replaced with +5s Nothl Projection Duration", t("REWORK")))
    W(li("Level 10 Talent Poison Touch Attack Range decreased from +300 to +200", b(300, 200)))
    W(ul_close())
    
    # Dragon Knight
    W(hero_header("Dragon Knight"))
    W(ability("Elder Dragon Form", slug="dragon_knight_elder_dragon_form"))
    W(ul_open())
    W(li("Bonus Move Speed decreased from 20/25/30/35 to 20", b([20, 25, 30, 35], 20)))
    W(ul_close())
    
    # Earth Spirit
    W(hero_header("Earth Spirit"))
    W(ability("Boulder Smash", slug="earth_spirit_boulder_smash"))
    W(ul_open())
    W(li("Damage rescaled from 120/180/240/300 to 110/180/250/320", b([120, 180, 240, 300], [110, 180, 250, 320])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Geomagnetic Grip Cooldown Reduction increased from 2s to 3s", b(2, 3)))
    W(li("Level 20 Talent Rolling Boulder Damage increased from +160 to +180", b(160, 180)))
    W(ul_close())
    
    # Ember Spirit
    W(hero_header("Ember Spirit"))
    W(ability("Sleight of Fist", slug="ember_spirit_sleight_of_fist"))
    W(ul_open())
    W(li("Bonus Hero Damage decreased from 40/80/120/160 to 25/70/115/160", b([40, 80, 120, 160], [25, 70, 115, 160])))
    W(ul_close())
    
    # Enchantress
    W(hero_header("Enchantress"))
    W(ul_open())
    W(li("Intelligence gain increased from 3.8 to 4.0", b(3.8, 4)))
    W(ul_close())
    
    # Faceless Void
    W(hero_header("Faceless Void"))
    W(facet_header("faceless_void_time_zone"))
    W(ul_open())
    W(li("Movement, Cast and Turn Speed manipulation decreased from 60% to 50%", b(60, 50)))
    W(li("No longer leashes enemies", t("DEL")))
    W(ul_close())
    
    # Hoodwink
    W(hero_header("Hoodwink"))
    W(ability("Acorn Shot", slug="hoodwink_acorn_shot"))
    W(ul_open())
    W(li("Bonus Damage increased from 40/80/120/160 to 45/90/135/180", b([40, 80, 120, 160], [45, 90, 135, 180])))
    W(ul_close())
    W(ability("Sharpshooter", slug="hoodwink_sharpshooter"))
    W(ul_open())
    W(li("Max Damage increased from 550/900/1250 to 600/975/1350", b([550, 900, 1250], [600, 975, 1350]), extra=inline_note("Damage with Hipshot facet increased from 412.5/675/937.5 to 450/731.25/1012.5 — " + b([412.5, 675, 937.5], [450, 731.25, 1012.5]))))
    W(ul_close())
    W(ability("Hunter's Boomerang", slug="hoodwink_hunters_boomerang"))
    W(ul_open())
    W(li("Movement Slow increased from 20% to 25%", b(20, 25)))
    W(li("Incoming Spell Damage Amp increased from 20% to 25%", b(20, 25)))
    W(ul_close())
    
    # Jakiro
    W(hero_header("Jakiro"))
    W(facet_header("jakiro_ice_breaker"))
    W(ul_open())
    W(li("Ice Path: Secondary Damage decreased from 75/125/175/225 to 50/100/150/200", b([75, 125, 175, 225], [50, 100, 150, 200])))
    W(ul_close())
    W(ability("Dual Breath", slug="jakiro_dual_breath"))
    W(ul_open())
    W(li("Mana Cost increased from 125/140/155/170 to 135/150/165/180", b([125, 140, 155, 170], [135, 150, 165, 180], l=True)))
    W(ul_close())
    
    # Juggernaut
    W(hero_header("Juggernaut"))
    W(ability("Omnislash", slug="juggernaut_omni_slash"))
    W(ul_open())
    W(li("Slash Jump Radius is no longer increased by AoE bonuses", t("DEL")))
    W(ul_close())
    
    # Keeper of the Light
    W(hero_header("Keeper of the Light"))
    W(ability("Chakra Magic", slug="keeper_of_the_light_chakra_magic"))
    W(ul_open())
    W(li("Self-cast bonus increased from 25% to 30%", b(25, 30)))
    W(ul_close())
    
    # Kez
    W(hero_header("Kez"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25 Talent Shodo Sai Mark Critical Strike increased from +75% to +100%", b(75, 100)))
    W(ul_close())
    
    # Kunkka
    W(hero_header("Kunkka"))
    W(ability("Tidebringer", slug="kunkka_tidebringer"))
    W(ul_open())
    W(li("Damage Bonus increased from 30/60/90/120 to 35/70/105/140", b([30, 60, 90, 120], [35, 70, 105, 140])))
    W(ul_close())
    
    # Legion Commander
    W(hero_header("Legion Commander"))
    W(facet_header("legion_commander_spoils_of_war"))
    W(ul_open())
    W(li("Duel: Press the Attack duration on allies after duel win is now decreased by 50%", t("NERF")))
    W(ul_close())
    
    # Lifestealer
    W(hero_header("Lifestealer"))
    W(facet_header("life_stealer_fleshfeast"))
    W(ul_open())
    W(li("Feast: Max HP per hero kill decreased from 20/25/30/35 to 15/20/25/30", b([20, 25, 30, 35], [15, 20, 25, 30])))
    W(ul_close())
    W(ability("Open Wounds", slug="life_stealer_open_wounds"))
    W(ul_open())
    W(li("Mana Cost increased from 75 to 100", b(75, 100, l=True)))
    W(ul_close())
    
    # Lina
    W(hero_header("Lina"))
    W(ability("Light Strike Array", slug="lina_light_strike_array"))
    W(ul_open())
    W(li("Mana Cost decreased from 100/115/130/145 to 100/110/120/130", b([100, 115, 130, 145], [100, 110, 120, 130], l=True)))
    W(ul_close())
    
    # Luna
    W(hero_header("Luna"))
    W(ability("Moon Glaives", slug="luna_moon_glaive"))
    W(ul_open())
    W(li("No longer bounce to attack-immune targets", t("MISC")))
    W(ul_close())
    
    # Lycan
    W(hero_header("Lycan"))
    W(ul_open())
    W(li("Base Strength increased from 26 to 28", b(26, 28)))
    W(li("Damage at level 1 increased from 50–55 to 52–57", br(50, 55, 52, 57)))
    W(ul_close())
    
    # Magnus
    W(hero_header("Magnus"))
    W(ul_open())
    W(li("Base Strength decreased from 25 to 23", b(25, 23)))
    W(li("Damage at level 1 decreased from 55–63 to 54–62", br(55, 63, 54, 62)))
    W(ul_close())
    W(ability("Shockwave", slug="magnataur_shockwave"))
    W(ul_open())
    W(li("Damage decreased from 90/160/230/300 to 75/150/225/300", b([90, 160, 230, 300], [75, 150, 225, 300])))
    W(ul_close())
    W(ability("Empower", slug="magnataur_empower"))
    W(ul_open())
    W(li("Self bonus decreased from 50% to 30%", b(50, 30)))
    W(ul_close())
    
    # Marci
    W(hero_header("Marci"))
    W(facet_header("marci_buddy_system"))
    W(ul_open())
    W(li("Bodyguard: Now also increases duration from 6s to 7s", b(6, 7)))
    W(ul_close())
    W(facet_header("marci_pickmeup"))
    W(ul_open())
    W(li("Rebound: Ally damage increased from 25% to 35%", b(25, 35)))
    W(ul_close())
    
    # Medusa
    W(hero_header("Medusa"))
    W(ul_open())
    W(li("Venomous Volley: No longer slows cast speed", t("MISC")))
    W(ul_close())
    
    # Meepo
    W(hero_header("Meepo"))
    W(facet_header("meepo_codependent"))
    W(ul_open())
    W(li("Divided We Stand: Armor bonus decreased from 2 to 1", b(2, 1)))
    W(ul_close())
    
    # Muerta
    W(hero_header("Muerta"))
    W(facet_header("muerta_ofrenda"))
    W(ul_open())
    W(li("Attack Speed Bonus increased from 15/25/35/45 to 20/30/40/50", b([15, 25, 35, 45], [20, 30, 40, 50])))
    W(ul_close())
    
    # Nature's Prophet
    W(hero_header("Nature's Prophet"))
    W(facet_header("furion_ironwood_treant"))
    W(ul_open())
    W(li("Nature's Call: Treant Health decreased from 800/1050/1300/1550 to 750/950/1150/1350", b([800, 1050, 1300, 1550], [750, 950, 1150, 1350])))
    W(ul_close())
    W(ability("Spirit of the Forest", slug="furion_spirit_of_the_forest"))
    W(ul_open())
    W(li("Bonus damage per tree decreased from 4% to 3%", b(4, 3)))
    W(ul_close())
    
    # Night Stalker
    W(hero_header("Night Stalker"))
    W(ul_open())
    W(li("Heart of Darkness: Bonus health regen at night decreased from 40% to 20%", b(40, 20)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Hunter in the Night Status Resistance decreased from 30% to 20%", b(30, 20)))
    W(ul_close())
    
    # Nyx Assassin
    W(hero_header("Nyx Assassin"))
    W(ability("Mind Flare", slug="nyx_assassin_jolt"))
    W(ul_open())
    W(li("Cooldown decreased from 13/11/9/7s to 11/9.5/8/6.5s", b([13, 11, 9, 7], [11, 9.5, 8, 6.5], l=True)))
    W(ul_close())
    
    # Omniknight
    W(hero_header("Omniknight"))
    W(facet_header("omniknight_omnipresent"))
    W(ability("Purification", slug="omniknight_purification"))
    W(ul_open())
    W(li("Cooldown decreased from 18/16/14/12s to 15/14/13/12s", b([18, 16, 14, 12], [15, 14, 13, 12], l=True)))
    W(ul_close())
    
    # Oracle
    W(hero_header("Oracle"))
    W(ability("Rain of Destiny", slug="oracle_rain_of_destiny"))
    W(ul_open())
    W(li("Damage/Heal per second decreased from 35 to 30", b(35, 30)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent -1s Purifying Flames Cooldown replaced with +25% Purifying Flames Enemy Damage", t("REWORK")))
    W(li("Level 20 Talent +30% Purifying Flames Enemy Damage replaced with -1s Purifying Flames Cooldown", t("REWORK")))
    W(ul_close())
    
    # Phantom Assassin
    W(hero_header("Phantom Assassin"))
    W(ability("Phantom Strike", slug="phantom_assassin_phantom_strike"))
    W(ul_open())
    W(li("Cast Range decreased from 1000 to 650/750/850/950", b(1000, [650, 750, 850, 950])))
    W(ul_close())
    
    # Primal Beast
    W(hero_header("Primal Beast"))
    W(facet_header("primal_beast_provoke_the_beast"))
    W(ul_open())
    W(li("Uproar: Now also provides stacks upon being Silenced", t("MISC")))
    W(ul_close())
    W(ability("Uproar", slug="primal_beast_uproar"))
    W(ul_open())
    W(li("Max Stacks increased from 5 to 6", b(5, 6)))
    W(ul_close())
    
    # Ringmaster
    W(hero_header("Ringmaster"))
    W(facet_header("ringmaster_sideshow_secrets"))
    W(ul_open())
    W(li("Crystal Ball: Now indicates the exact position of each enemy hero in the area without revealing their identity", t("MISC")))
    W(li("Unicycle: No longer gets knocked off if the damage taken is below 20", t("MISC")))
    W(li("No longer gets knocked off from any damage for 1.5s after mounting the unicycle", t("MISC")))
    W(li("Can now cast non-channeling spells and pick up runes without dismounting the unicycle", t("MISC"), extra=inline_note("Still requires Ringmaster to be facing in the spell direction")))
    W(li("Weighted Pie: Now also slows movement of the affected enemy by 45%. Similarly to vision, movement speed is recovering over the debuff time", t("MISC")))
    W(ul_close())
    
    # Silencer
    W(hero_header("Silencer"))
    W(ul_open())
    W(li("Brain Drain: If Silencer is out of range, Intelligence will now be stolen only if the dying enemy is debuffed by Silencer the moment they die", t("MISC"), extra=inline_note("This effect used to have a grace period equal to the full Assist-gaining duration even when the debuff was removed")))
    W(ul_close())
    
    # Skywrath Mage
    W(hero_header("Skywrath Mage"))
    W(ability("Arcane Bolt", slug="skywrath_mage_arcane_bolt"))
    W(ul_open())
    W(li("Mana Cost decreased from 85 to 70", b(85, 70, l=True)))
    W(ul_close())
    
    # Snapfire
    W(hero_header("Snapfire"))
    W(ability("Lil' Shredder", slug="snapfire_lil_shredder"))
    W(ul_open())
    W(li("Base Damage per shot increased from 20/35/50/65 to 25/40/55/70", b([20, 35, 50, 65], [25, 40, 55, 70])))
    W(ul_close())
    W(ability("Mortimer Kisses", slug="snapfire_mortimer_kisses"))
    W(ul_open())
    W(li("No longer interrupted when Snapfire uses items/abilities that can be cast while channeling (Glimmer Cape, etc.)", t("MISC"), extra=inline_note("This also fixes being interrupted when receiving Madstone")))
    W(ul_close())
    
    # Templar Assassin
    W(hero_header("Templar Assassin"))
    W(ability("Refraction", slug="templar_assassin_refraction"))
    W(ul_open())
    W(li("Cooldown decreased from 16s to 14s", b(16, 14, l=True)))
    W(li("Number of instances increased from 2/3/4/5 to 3/4/5/6", b([2, 3, 4, 5], [3, 4, 5, 6])))
    W(ul_close())
    W(ability("Meld", slug="templar_assassin_meld"))
    W(ul_open())
    W(li("Fixed not applying to both attacks if Meld was used twice in quick succession", t("MISC")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25 Talent Refraction Instances increased from +3 to +4", b(3, 4)))
    W(ul_close())
    
    # Terrorblade
    W(hero_header("Terrorblade"))
    W(ability("Conjure Image", slug="terrorblade_conjure_image"))
    W(ul_open())
    W(li("Illusion Damage Taken decreased from 275% to 250%", b(275, 250, l=True)))
    W(ul_close())
    
    # Tidehunter
    W(hero_header("Tidehunter"))
    W(facet_header("tidehunter_sizescale"))
    W(ability("Dead in the Water", slug="tidehunter_dead_in_the_water"))
    W(ul_open())
    W(li("Cooldown increased from 25s to 35s", b(25, 35, l=True)))
    W(ul_close())
    
    # Timbersaw
    W(hero_header("Timbersaw"))
    W(ability("Timber Chain", slug="shredder_timber_chain"))
    W(ul_open())
    W(li("Damage rescaled from 50/95/140/185 to 45/100/155/210", b([50, 95, 140, 185], [45, 100, 155, 210])))
    W(ul_close())
    W(ability("Reactive Armor", slug="shredder_reactive_armor"))
    W(ul_open())
    W(li("Bonus HP Regen increased from 0.3/0.4/0.5/0.6 to 0.4/0.5/0.6/0.7", b([0.3, 0.4, 0.5, 0.6], [0.4, 0.5, 0.6, 0.7])))
    W(ul_close())
    
    # Tinker
    W(hero_header("Tinker"))
    W(ul_open())
    W(li("Defense Matrix: Mana Cost increased from 80/95/110/125 to 90/105/120/135", b([80, 95, 110, 125], [90, 105, 120, 135], l=True)))
    W(ul_close())
    W(ability("Laser", slug="tinker_laser"))
    W(ul_open())
    W(li("Aghanim's Scepter size and health reductions decreased from 15% to 13%", b(15, 13)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Defense Matrix Damage Barrier decreased from +75 to +60", b(75, 60)))
    W(ul_close())
    
    # Tiny
    W(hero_header("Tiny"))
    W(facet_header("tiny_crash_landing"))
    W(ul_open())
    W(li("Toss: Movement Slow increased from 15/20/25/30% to 20/25/30/35%", b([15, 20, 25, 30], [20, 25, 30, 35])))
    W(li("Attack Slow increased from 10/20/30/40 to 15/25/35/45", b([10, 20, 30, 40], [15, 25, 35, 45])))
    W(ul_close())
    W(ability("Grow", slug="tiny_grow"))
    W(ul_open())
    W(li("Bonus Damage decreased from 60/120/180 to 55/110/165", b([60, 120, 180], [55, 110, 165])))
    W(li("Movement Speed Bonus rescaled from 10/20/30 to 15", b([10, 20, 30], 15)))
    W(ul_close())
    
    # Warlock
    W(hero_header("Warlock"))
    W(ability("Eldritch Summoning", slug="warlock_eldritch_summoning"))
    W(ul_open())
    W(li("Imp explosion delay increased from 0.2s to 0.3s", b(0.2, 0.3)))
    W(ul_close())
    
    # Weaver
    W(hero_header("Weaver"))
    W(ability("The Swarm", slug="weaver_the_swarm"))
    W(ul_open())
    W(li("Bugs are now destroyed if the host unit becomes invulnerable", t("MISC"), extra=inline_note("i.e. using Eul's Scepter of Divinity, etc")))
    W(ul_close())
    
    # Windranger
    W(hero_header("Windranger"))
    W(ul_open())
    W(li("Base Damage increased by 3", bstat_h("Windranger", "AttackDamageMin", "7.38b", 3), extra=note_box(hero="Windranger", field="AttackDamageMin", before_patch="7.38b")))
    W(li("Damage on level 1 increased from 44–56 to 47–59", t("BUFF")))
    W(ul_close())
    W(facet_header("windrunner_killshot"))
    W(ul_open())
    W(li("Powershot: Execute no longer goes through any death denial effects (Dazzle's Shallow Grave, Oracle's False Promise, etc.)", t("MISC")))
    W(ul_close())
    
    # Wraith King
    W(hero_header("Wraith King"))
    W(facet_header("skeleton_king_facet_bone_guard"))
    W(ul_open())
    W(li("Cooldown decreased from 50s to 42s", b(50, 42, l=True)))
    W(li("Skeleton Duration increased from 40s to 46s", b(40, 46)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent +25%/-25% Bone Guard Duration / Cooldown replaced with +2s Wraithfire Blast Slow Duration", t("REWORK")))
    W(ul_close())
    W(ability("Wraithfire Blast", slug="skeleton_king_hellfire_blast"))
    W(ul_open())
    W(li("Cooldown decreased from 17/14/11/8s to 14/12/10/8s", b([17, 14, 11, 8], [14, 12, 10, 8], l=True)))
    W(ul_close())
    W(ability("Reincarnation", slug="skeleton_king_reincarnation"))
    W(ul_open())
    W(li("Mana Cost increased from 200 to 225", b(200, 225, l=True)))
    W(ul_close())

    write_footer()
    save_html('patches/7.38c.html')
