from patch.api import *

def build():
    write_head("7.38b", "05.03.2025")

    W(section("General Updates"))
    W(ul_open())
    W(li("Item grace period for swapping into the main inventory without a cooldown increased from 3s to 5s", b(3, 5, l=True)))
    W(li("Tormentor: Gold to each team member on death decreased from 250 to 175", b(250, 175)))
    W(li("Tormentor: Unyielding Shield: Base Damage absorb increased from 1900 to 2100", b(1900, 2100)))
    W(li("Tormentor: Unyielding Shield: Base Barrier regeneration increased from 30 to 40", b(30, 40)))
    W(li("Removed several trees around camps, making it easier for additional paths to be cut through:", t("DEL"), extra=inline_note("To the right of Dire Ancient camp by Safelane Tier 1 Tower")))
    W(li("Lotuses can no longer be picked up by Meepo clones, Arc Warden's Tempest Double or Dazzle's Nothl Projection", t("MISC")))
    W(li("Moved the spawn box of the Radiant Safelane tier 1 hard pull camp a little bit down, removing an inaccessible camp block spot that could be created by chopping down a tree", t("MISC")))
    W(li("To the right of Dire Medium camp between mid and top Tier 2 Towers", t("MISC")))
    W(li("To the top of Dire Hard camp nearest to mid Tier 1 Tower", t("MISC")))
    W(li("To the top of the Dire Jungle high-ground Medium camp", t("MISC")))
    W(li("To the right of the Dire offlane Tier 2 Tower Medium camp", t("MISC")))
    W(li("To the right of the Radiant Hard Camp by mid tier 1", t("MISC")))
    W(li("To the right and left of the Radiant Hard Camp by offlane Tier 1 Tower", t("MISC")))
    W(li("To the left of the Radiant Safelane Tier 2 Tower Medium water camp", t("MISC")))
    W(ul_close())

    # ===== ITEM UPDATES =====
    W(section("Item Updates"))
    W(item_header("Eye of Skadi"))
    W(ul_open())
    W(li("Cold Attack Melee Movement Slow increased from 20% to 25%", b(20, 25)))
    W(li("Cold Attack no longer has a separate attack speed slow value against melee targets", t("MISC"), extra=inline_note("As a result, attack slow against melee units increased from 10% to 20% — " + b(10, 20))))
    W(ul_close())
    W(item_header("Glimmer Cape"))
    W(ul_open())
    W(li("Glimmer Bonus Movement Speed decreased from 40 to 20", b(40, 20)))
    W(li("Glimmer Mana Cost increased from 90 to 125", b(90, 125, l=True)))
    W(ul_close())
    W(item_header("Heaven's Halberd", changed=True))
    W(auto_components_change("Heaven's Halberd", "7.38b"))
    W(ul_open())
    W(li("Recipe cost increased from 275 to 450 " + b(275, 450, l=True) + ". Total cost unchanged", t("MISC")))
    W(ul_close())
    W(item_header("Khanda"))
    W(ul_open())
    W(li("Empower Spell Debuff Duration increased from 3s to 4s", b(3, 4)))
    W(li("Empower Spell Cooldown decreased from 12s to 10s", b(12, 10, l=True)))
    W(ul_close())
    W(item_header("Orb of Corrosion"))
    W(ul_open())
    W(li("Agility bonus decreased from +8 to +7", b(8, 7)))
    W(li("Corrosion Melee Movement Slow increased from 6% to 8%", b(6, 8)))
    W(ul_close())
    W(item_header("Orb of Frost"))
    W(ul_open())
    W(li("Frost Melee Movement Slow increased from 5% to 6%", b(5, 6)))
    W(ul_close())
    W(item_header("Orchid Malevolence"))
    W(ul_open())
    W(li("Mana Regen bonus decreased from +3.25 to +3", b(3.25, 3)))
    W(li("Attack Speed bonus decreased from +40 to +35", b(40, 35)))
    W(ul_close())
    W(item_header("Bloodthorn"))
    W(ul_open())
    W(li("Mana Regen bonus decreased from +3.5 to +3.25", b(3.5, 3.25)))
    W(li("Attack Speed bonus decreased from +100 to +95", b(100, 95)))
    W(ul_close())

    # ===== NEUTRAL ITEM UPDATES =====
    W(section("Neutral Item Updates"))

    W(plain_header("Artifact changes", dynamics=False, sublabel=True))
    W(item_header("Mana Draught"))
    W(ul_open())
    W(li("Bottoms Up mana restored rescaled from 60 + 2% of Caster's Max Mana to 30 + 4% of Caster's Max Mana", t("REWORK")))
    W(ul_close())
    W(item_header("Orb of Destruction"))
    W(ul_open())
    W(li("Impeding Corruption duration decreased from 5s to 3s", b(5, 3)))
    W(ul_close())
    W(item_header("Pig Pole"))
    W(ul_open())
    W(li("Pig, Out! bonus movement speed increased from 15% to 20%", b(15, 20)))
    W(li("Pig, Out! cooldown decreased from 25s to 20s", b(25, 20, l=True)))
    W(li("Pig, Out! duration decreased from 4s to 3s", b(4, 3)))
    W(ul_close())
    W(item_header("Pollywog Charm"))
    W(ul_open())
    W(li("Ribbit duration increased from 10s to 14s", b(10, 14)))
    W(ul_close())
    W(item_header("Ripper's Lash"))
    W(ul_open())
    W(li("Flay cooldown decreased from 30s to 25s", b(30, 25, l=True)))
    W(ul_close())
    W(item_header("Trusty Shovel"))
    W(ul_open())
    W(li("Dig cooldown increased from 60s to 70s", b(60, 70, l=True)))
    W(ul_close())
    W(item_header("Brigand's Blade"))
    W(ul_open())
    W(li("Dark Mercy enemy HP increment increased from 5% to 7%", b(5, 7)))
    W(ul_close())
    W(item_header("Essence Ring"))
    W(ul_open())
    W(li("Life Essence duration decreased from 15s to 10s", b(15, 10)))
    W(li("Life Essence mana cost increased from 150 to 160", b(150, 160, l=True)))
    W(ul_close())
    W(item_header("Iron Talon"))
    W(ul_open())
    W(li("Chop cooldown decreased from 20s to 15s", b(20, 15, l=True)))
    W(ul_close())
    W(item_header("Searing Signet"))
    W(ul_open())
    W(li("Burn Through damage threshold increased from 40 to 55", b(40, 55)))
    W(ul_close())
    W(item_header("Gale Guard"))
    W(ul_open())
    W(li("Cyclonic Shield damage Barrier decreased from 400 to 250", b(400, 250)))
    W(ul_close())
    W(item_header("Gunpowder Gauntlet"))
    W(ul_open())
    W(li("Beat the Crowd now also deals 50% of the bonus magical damage to enemies in the splash radius", t("NEW")))
    W(li("Beat the Crowd splash damage now bypasses physical damage block", t("BUFF")))
    W(ul_close())
    W(item_header("Ninja Gear"))
    W(ul_open())
    W(li("Solitary Disguise mana cost increased from 0 to 100", b(0, 100, l=True)))
    W(ul_close())
    W(item_header("Serrated Shiv"))
    W(ul_open())
    W(li("Gut 'Em current health as physical damage decreased from 10% to 8%", b(10, 8)))
    W(ul_close())
    W(item_header("Crippling Crossbow"))
    W(ul_open())
    W(li("Hobble cast range increased from 600 to 800", b(600, 800)))
    W(ul_close())
    W(item_header("Mind Breaker"))
    W(ul_open())
    W(li("Silence Strike silence duration decreased from 2s to 1.5s", b(2, 1.5)))
    W(ul_close())
    W(item_header("Pyrrhic Cloak"))
    W(ul_open())
    W(li("Retribution damage reflection increased from 60% to 75%", b(60, 75)))
    W(ul_close())
    W(item_header("Fallen Sky"))
    W(ul_open())
    W(li("Fallen Sky cooldown increased from 15s to 25s", b(15, 25, l=True)))
    W(ul_close())
    W(item_header("Pirate Hat"))
    W(ul_open())
    W(li("Plunder bonus gold for being the killer of a hero increased from 150 to 400", b(150, 400)))
    W(ul_close())
    W(item_header("Unrelenting Eye"))
    W(ul_open())
    W(li("Relentless now also provides +10% status resistance per enemy within 300 units", t("NEW")))
    W(ul_close())

    W(plain_header("Enchantment changes", dynamics=False, sublabel=True))
    W(enchant_header("Brawny"))
    W(ul_open())
    W(li("Health bonus decreased from +125/175/225/275 to +125/165/205/245", b([125, 175, 225, 275], [125, 165, 205, 245])))
    W(ul_close())
    W(enchant_header("Mystical"))
    W(ul_open())
    W(li("Magic Resistance bonus decreased from +0/10/16/22% to +0/10/14/18%", b([0, 10, 16, 22], [0, 10, 14, 18])))
    W(ul_close())
    W(enchant_header("Vampiric"))
    W(ul_open())
    W(li("Lifesteal bonus decreased from +12/16/20% to +12/14/16%", b([12, 16, 20], [12, 14, 16])))
    W(li("Spell Lifesteal bonus decreased from +8/12/16% to +8/10/12%", b([8, 12, 16], [8, 10, 12])))
    W(ul_close())

    # ===== HERO UPDATES =====
    W(section("Hero Updates"))

    # Abaddon
    W(hero_header("Abaddon"))
    W(ul_open())
    W(li("Base Mana Regen decreased from 0.25 to 0", b(0.25, 0)))
    W(ul_close())
    W(facet_header("abaddon_mephitic_shroud"))
    W(ul_open())
    W(li("Aphotic Shield: Duration decreased from 17s to 14s", b(17, 14)))
    W(ul_close())
    W(ability("Mist Coil", slug="abaddon_death_coil"))
    W(ul_open())
    W(li("Damage/Heal decreased from 100/175/250/325 to 80/150/220/290", b([100, 175, 250, 325], [80, 150, 220, 290])))
    W(li("Cast Range rescaled from 600/625/650/675 to 625", b([600, 625, 650, 675], 625)))
    W(ul_close())
    W(ability("Aphotic Shield", slug="abaddon_aphotic_shield"))
    W(ul_open())
    W(li("Duration decreased from 15s to 12s", b(15, 12)))
    W(li("Mana Cost increased from 95/110/125/140 to 110/120/130/140", b([95, 110, 125, 140], [110, 120, 130, 140], l=True)))
    W(ul_close())
    W(ability("Borrowed Time", slug="abaddon_borrowed_time"))
    W(ul_open())
    W(li("Aghanim's Scepter radius changed from 900 to Mist Coil's Cast Range", t("REWORK")))
    W(ul_close())

    # Alchemist
    W(hero_header("Alchemist"))
    W(ability("Greevil's Greed", slug="alchemist_goblins_greed"))
    W(ul_open())
    W(li("Gifting Aghanim's Scepters no longer provides Spell Amplification", t("DEL")))
    W(ul_close())

    # Ancient Apparition
    W(hero_header("Ancient Apparition"))
    W(ul_open())
    W(li("Agility gain decreased from 2.2 to 2.0", b(2.2, 2)))
    W(ul_close())

    # Arc Warden
    W(hero_header("Arc Warden"))
    W(facet_header("arc_warden_runed_replica"))
    W(ul_open())
    W(li("Tempest Double: Rune Duration increased from 10s to 12s", b(10, 12)))
    W(ul_close())

    # Beastmaster
    W(hero_header("Beastmaster"))
    W(ul_open())
    W(li("Base Damage decreased by 3", bstat_h("Beastmaster", "AttackDamageMin", "7.38", -3), extra=note_box(hero="Beastmaster", field="AttackDamageMin", before_patch="7.38")))
    W(li("Damage at level 1 decreased by 3 (from 56-60 to 53-57)", br(56, 60, 53, 57)))
    W(ul_close())

    # Brewmaster
    W(hero_header("Brewmaster"))
    W(ability("Belligerent", slug="brewmaster_belligerent", innate=True))
    W(ul_open())
    W(li("Duration on respawn increased from 30s to 45s", b(30, 45)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent +200 Thunder Clap AoE replaced with +1.5s Thunder Clap Duration", t("REWORK")))
    W(ul_close())

    # Broodmother
    W(hero_header("Broodmother"))
    W(ul_open())
    W(li("Base Damage decreased by 2", bstat_h("Broodmother", "AttackDamageMin", "7.38", -2), extra=note_box(hero="Broodmother", field="AttackDamageMin", before_patch="7.38")))
    W(li("Damage at level 1 decreased by 2 (from 47-53 to 45-51)", br(47, 53, 45, 51)))
    W(ul_close())
    W(facet_header("broodmother_necrotic_webs"))
    W(ul_open())
    W(li("Spin Web: Health regen reduction does not affect enemies in fountain", t("MISC")))
    W(ul_close())

    # Chen
    W(hero_header("Chen"))
    W(ability("Summon Convert", slug="chen_summon_convert", innate=True))
    W(ul_open())
    W(li("Convert's abilities now also level up with Holy Persuasion", t("NEW")))
    W(ul_close())

    # Dark Seer
    W(hero_header("Dark Seer"))
    W(ul_open())
    W(li("Base Armor decreased by 1", bstat_h("Dark Seer", "ArmorPhysical", "7.38", -1), extra=note_box(hero="Dark Seer", field="ArmorPhysical", before_patch="7.38")))
    W(ul_close())
    W(ability("Aggrandize", slug="dark_seer_aggrandize", innate=True))
    W(ul_open())
    W(li("Restore percentage per hero level decreased from 2% to 1.5%", b(2, 1.5)))
    W(ul_close())

    # Dazzle
    W(hero_header("Dazzle"))
    W(facet_header("dazzle_facet_nothl_boon"))
    W(ul_open())
    W(li("Weave: Allies now receive 5% extra healing from Dazzle per stack", t("NEW")))
    W(ul_close())
    W(ability("Poison Touch", slug="dazzle_poison_touch"))
    W(ul_open())
    W(li("Duration decreased from 5/6/7/8s to 3.5/5/6.5/8s", b([5, 6, 7, 8], [3.5, 5, 6.5, 8])))
    W(ul_close())
    W(ability("Nothl Projection", slug="dazzle_nothl_projection"))
    W(ul_open())
    W(li("Shadow Wave Cooldown Reduction decreased from 30/45/60% to 30/40/50%", b([30, 45, 60], [30, 40, 50])))
    W(ul_close())

    # Dragon Knight
    W(hero_header("Dragon Knight"))
    W(facet_header("dragon_knight_fire_dragon"))
    W(ul_open())
    W(li("Dragon Tail: AoE while in Dragon Form decreased from 175 to 100", b(175, 100)))
    W(li("Wyrm's Wrath: Magic Damage on Attacks decreased from 10/20/30/40 to 6/12/18/24", b([10, 20, 30, 40], [6, 12, 18, 24])))
    W(ul_close())

    # Ember Spirit
    W(hero_header("Ember Spirit"))
    W(ul_open())
    W(li("Strength gain decreased from 2.6 to 2.3", b(2.6, 2.3)))
    W(ul_close())

    # Hoodwink
    W(hero_header("Hoodwink"))
    W(ability("Bushwhack", slug="hoodwink_bushwhack"))
    W(ul_open())
    W(li("Cooldown rescaled from 14s to 15/14/13/12s", b(14, [15, 14, 13, 12], l=True)))
    W(ul_close())

    # Huskar
    W(hero_header("Huskar"))
    W(ability("Inner Fire", slug="huskar_inner_fire"))
    W(ul_open())
    W(li("Damage decreased from 120/180/240/300 to 105/170/235/300", b([120, 180, 240, 300], [105, 170, 235, 300])))
    W(ul_close())

    # Invoker
    W(hero_header("Invoker"))
    W(facet_header("invoker_quas_focus"))
    W(ul_open())
    W(li("Ghost Walk: Aghanim's Scepter ally duration increased from 20s to 30s", b(20, 30)))
    W(li("Cold Snap: When Cold Snap triggers, Invoker now also restores 5 mana in addition to existing healing based on Quas", t("NEW")))
    W(ul_close())
    W(facet_header("invoker_wex_focus"))
    W(ul_open())
    W(li("Alacrity: Attack range bonus increased from 50/60/70/80/90/100/110/120/130/140 to 60/70/80/90/100/110/120/130/140/150", b([50, 60, 70, 80, 90, 100, 110, 120, 130, 140], [60, 70, 80, 90, 100, 110, 120, 130, 140, 150])))
    W(ul_close())
    W(facet_header("invoker_exort_focus"))
    W(ul_open())
    W(li("Sun Strike: Aghanim's Scepter Cataclysm cooldown increased from 60 to 75 seconds", b(60, 75, l=True)))
    W(ul_close())
    W(ability("Forge Spirit", slug="invoker_forge_spirit"))
    W(ul_open())
    W(li("Attack range rescaled from 300/365/430/495/560/625/690/755/820/885 to 305/360/415/470/525/580/635/690/745/800", b([300, 365, 430, 495, 560, 625, 690, 755, 820, 885], [305, 360, 415, 470, 525, 580, 635, 690, 745, 800])))
    W(ul_close())

    # Jakiro
    W(hero_header("Jakiro"))
    W(facet_header("jakiro_ice_breaker"))
    W(ul_open())
    W(li("Ice Path: Path Duration decreased from 6s to 5s", b(6, 5)))
    W(ul_close())
    W(ability("Ice Path", slug="jakiro_ice_path"))
    W(ul_open())
    W(li("Cooldown increased from 18/15/12/9s to 20/17/14/11s", b([18, 15, 12, 9], [20, 17, 14, 11], l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent -1.5s Ice Path Cooldown replaced with +60 Ice Path Base Damage", t("REWORK")))
    W(ul_close())

    # Keeper of the Light
    W(hero_header("Keeper of the Light"))
    W(ability("Spirit Form", slug="keeper_of_the_light_spirit_form"))
    W(ul_open())
    W(li("Cooldown decreased from 85s to 85/80/75s", b(85, [85, 80, 75], l=True)))
    W(li("Duration increased from 40s to 40/45/50s", b(40, [40, 45, 50])))
    W(li("Illuminate Heal increased from 50/60/70% to 70%", b([50, 60, 70], 70)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent +15s Spirit Form Duration replaced with +10% Spirit Form Movement Speed", t("REWORK")))
    W(ul_close())

    # Kez
    W(hero_header("Kez"))
    W(ul_open())
    W(li("Base Intelligence increased from 18 to 20", b(18, 20)))
    W(li("Strength gain increased from 2.6 to 2.8", b(2.6, 2.8)))
    W(ul_close())
    W(facet_header("kez_shadowhawk"))
    W(ul_open())
    W(li("Now scales with ultimate abilities instead of Shodo Sai", t("REWORK")))
    W(li("Shodo Sai: Invis Bonus Crit rescaled from 50% to 40/60/80/100%", b(50, [40, 60, 80, 100])))
    W(ul_close())
    W(ability("Grappling Claw", slug="kez_grappling_claw"))
    W(ul_open())
    W(li("Lifesteal increased from 50/75/100/125% to 65/85/105/125%", b([50, 75, 100, 125], [65, 85, 105, 125])))
    W(ul_close())
    W(ability("Shodo Sai", slug="kez_shodo_sai"))
    W(ul_open())
    W(li("Can now block all physical attack sources (still can't Mark non-hero units)", t("BUFF")))
    W(ul_close())
    W(ability("Raptor Dance", slug="kez_raptor_dance"))
    W(ul_open())
    W(li("Invulnerability period increased from 0.1s to 0.2s", b(0.1, 0.2)))
    W(ul_close())

    # Leshrac
    W(hero_header("Leshrac"))
    W(facet_header("leshrac_attacks_mana"))
    W(ul_open())
    W(li("Damage as mana restore increased from 10/18/26/34% to 14/21/28/35%", b([10, 18, 26, 34], [14, 21, 28, 35])))
    W(ul_close())
    W(ability("Diabolic Edict", slug="leshrac_diabolic_edict"))
    W(ul_open())
    W(li("Mana Cost increased from 90/110/130/150 to 90/120/150/180", b([90, 110, 130, 150], [90, 120, 150, 180], l=True)))
    W(ul_close())
    W(ability("Lightning Storm", slug="leshrac_lightning_storm"))
    W(ul_open())
    W(li("No longer slows attack speed", t("DEL")))
    W(ul_close())

    # Lifestealer
    W(hero_header("Lifestealer"))
    W(ul_open())
    W(li("Base Agility decreased by 4", bstat_h("Lifestealer", "AttributeBaseAgility", "7.38", -4), extra=note_box(hero="Lifestealer", field="AttributeBaseAgility", before_patch="7.38")))
    W(ul_close())
    W(facet_header("life_stealer_fleshfeast"))
    W(ul_open())
    W(li("Feast: Max HP per hero kill decreased from 25/35/45/55 to 20/25/30/35", b([25, 35, 45, 55], [20, 25, 30, 35])))
    W(ul_close())
    W(ability("Feast", slug="life_stealer_feast"))
    W(ul_open())
    W(li("Max HP per hero kill decreased from 15 to 10", b(15, 10)))
    W(ul_close())
    W(ability("Infest", slug="life_stealer_infest"))
    W(ul_open())
    W(li("Aghanim's Scepter attack rate improved from 1.25s to 1s", b(1.25, 1)))
    W(li("Aghanim's Scepter no longer disarms targeted enemy hero", t("DEL")))
    W(ul_close())

    # Lina
    W(hero_header("Lina"))
    W(ability("Laguna Blade", slug="lina_laguna_blade"))
    W(ul_open())
    W(li("Aghanim's Shard damage converted increased from 75% to 100%", b(75, 100)))
    W(ul_close())

    # Lycan
    W(hero_header("Lycan"))
    W(facet_header("lycan_spirit_wolves"))
    W(ul_open())
    W(li("Summon Wolves: Bonus health per wolf increased from 50/100/150/200 to 60/115/170/225", b([50, 100, 150, 200], [60, 115, 170, 225])))
    W(ul_close())

    # Magnus
    W(hero_header("Magnus"))
    W(ability("Magnus", slug="magnataur_magnus", innate=True))
    W(ul_open())
    W(li("Eternal Empowerment: Empower: Max self bonus decreased from 10/15/20/25% to 8/12/16/20%", b([10, 15, 20, 25], [8, 12, 16, 20])))
    W(ul_close())
    W(ability("Skewer", slug="magnataur_skewer"))
    W(ul_open())
    W(li("Distance decreased from 900/975/1050/1125 to 800/900/1000/1100", b([900, 975, 1050, 1125], [800, 900, 1000, 1100])))
    W(li("Aghanim's Shard Distance decreased from 1175/1250/1325/1400 to 1075/1175/1275/1375", b([1175, 1250, 1325, 1400], [1075, 1175, 1275, 1375])))
    W(ul_close())

    # Marci
    W(hero_header("Marci"))
    W(ability("Rebound", slug="marci_companion_run"))
    W(ul_open())
    W(li("Impact Damage decreased from 80/160/240/320 to 75/150/225/300", b([80, 160, 240, 320], [75, 150, 225, 300])))
    W(li("Aghanim's Shard Impact Damage decreased from 96/192/288/384 to 90/180/270/360", b([96, 192, 288, 384], [90, 180, 270, 360])))
    W(ul_close())

    # Medusa
    W(hero_header("Medusa"))
    W(ability("Venomous Volley", slug="medusa_venomous_volley", innate=True))
    W(ul_open())
    W(li("Attacks required to apply poison increased from 5 to 6", b(5, 6)))
    W(ul_close())

    # Meepo
    W(hero_header("Meepo"))
    W(facet_header("meepo_codependent"))
    W(ul_open())
    W(li("Attack speed bonus decreased from 7% to 5%", b(7, 5)))
    W(ul_close())

    # Mirana
    W(hero_header("Mirana"))
    W(facet_header("mirana_starstruck"))
    W(ul_open())
    W(li("Starstorm: Blind Duration decreased from 3.5/4/4.5/5s to 3s", b([3.5, 4, 4.5, 5], 3)))
    W(ul_close())

    # Monkey King
    W(hero_header("Monkey King"))
    W(ability("Wukong's Command", slug="monkey_king_wukongs_command"))
    W(ul_open())
    W(li("Soldiers no longer receive a copy of Monkey King's neutral item", t("DEL")))
    W(ul_close())

    # Muerta
    W(hero_header("Muerta"))
    W(ability("The Calling", slug="muerta_the_calling"))
    W(ul_open())
    W(li("No longer slows attack speed", t("DEL")))
    W(ul_close())

    # Nature's Prophet
    W(hero_header("Nature's Prophet"))
    W(ability("Wrath of Nature", slug="furion_wrath_of_nature"))
    W(ul_open())
    W(li("Aghanim's Scepter no longer reduces cooldown by 25s", t("DEL")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Sprout Leashes replaced with -15s Wrath of Nature cooldown", t("REWORK")))
    W(li("Level 10 Talent Wrath of Nature Base Damage bonus decreased from +30 to +25", b(30, 25)))
    W(ul_close())

    # Night Stalker
    W(hero_header("Night Stalker"))
    W(facet_header("night_stalker_dayswap"))
    W(ul_open())
    W(li("Hunter in the Night: Move Speed decreased from 16/22/28/34/40% to 10/22/28/34/40%", b([16, 22, 28, 34, 40], [10, 22, 28, 34, 40])))
    W(ul_close())
    W(facet_header("night_stalker_voidbringer"))
    W(ul_open())
    W(li("Void: AoE on level 5 increased from 300 to 350", b(300, 350)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Dark Ascension Duration decreased from +6s to +5s", b(6, 5)))
    W(ul_close())

    # Phantom Lancer
    W(hero_header("Phantom Lancer"))
    W(ability("Juxtapose", slug="phantom_lancer_juxtapose"))
    W(ul_open())
    W(li("Illusion Trigger Chance increased from 8% to 9%", b(8, 9)))
    W(ul_close())

    # Primal Beast
    W(hero_header("Primal Beast"))
    W(facet_header("primal_beast_provoke_the_beast"))
    W(ul_open())
    W(li("Uproar: Stacks gained per debuff increased from 2 to 3", b(2, 3)))
    W(ul_close())
    W(facet_header("primal_beast_ferocity"))
    W(ul_open())
    W(li("Pulverize: Stack duration decreased from 20s to 15s", b(20, 15)))
    W(ul_close())

    # Spectre
    W(hero_header("Spectre"))
    W(facet_header("spectre_forsaken"))
    W(ul_open())
    W(li("Desolate: Damage Multiplier increased from 1.75x to 2x", b(1.75, 2)))
    W(ul_close())

    # Storm Spirit
    W(hero_header("Storm Spirit"))
    W(ul_open())
    W(li("Intelligence gain decreased from 3.9 to 3.7", b(3.9, 3.7)))
    W(ul_close())

    # Tidehunter
    W(hero_header("Tidehunter"))
    W(ability("Anchor Smash", slug="tidehunter_anchor_smash"))
    W(ul_open())
    W(li("Damage Reduction decreased from 30/40/50/60% to 25/30/35/40%", b([30, 40, 50, 60], [25, 30, 35, 40])))
    W(ul_close())
    W(ability("Dead in the Water", slug="tidehunter_dead_in_the_water"))
    W(ul_open())
    W(li("Damage decreased from 200 to 100", b(200, 100)))
    W(li("Mana Cost increased from 80 to 110", b(80, 110, l=True)))
    W(ul_close())

    # Tiny
    W(hero_header("Tiny"))
    W(ability("Grow", slug="tiny_grow"))
    W(ul_open())
    W(li("Bonus Armor decreased from 10/17/24 to 5/10/15", b([10, 17, 24], [5, 10, 15])))
    W(ul_close())

    # Troll Warlord
    W(hero_header("Troll Warlord"))
    W(ability("Fervor", slug="troll_warlord_fervor"))
    W(ul_open())
    W(li("Aghanim's Shard no longer procs additional attacks when attacking a building or ward-type unit", t("DEL")))
    W(ul_close())

    # Tusk
    W(hero_header("Tusk"))
    W(facet_header("tusk_facet_fist_bump"))
    W(ul_open())
    W(li("Bonus damage increased from 20/45/70/95 to 20/50/80/110", b([20, 45, 70, 95], [20, 50, 80, 110])))
    W(ul_close())

    # Venomancer
    W(hero_header("Venomancer"))
    W(ability("Venomous Gale", slug="venomancer_venomous_gale"))
    W(ul_open())
    W(li("Slow decreased from 50% to 35/40/45/50%", b(50, [35, 40, 45, 50])))
    W(ul_close())

    # Visage
    W(hero_header("Visage"))
    W(ability("Grave Chill", slug="visage_grave_chill"))
    W(ul_open())
    W(li("Duration decreased from 6s to 5s", b(6, 5)))
    W(li("Move Speed Drain decreased from 15/20/25/30% to 12/16/20/24%", b([15, 20, 25, 30], [12, 16, 20, 24])))
    W(ul_close())

    # Warlock
    W(hero_header("Warlock"))
    W(facet_header("warlock_grimoire"))
    W(ul_open())
    W(li("XP per kill/assist decreased from 250 to 200", b(250, 200)))
    W(ul_close())

    # Weaver
    W(hero_header("Weaver"))
    W(ability("The Swarm", slug="weaver_the_swarm"))
    W(ul_open())
    W(li("Attack Interval increased from 1.15/1.0/0.85/0.7s to 1.2/1.05/0.9/0.75s", b([1.15, 1, 0.85, 0.7], [1.2, 1.05, 0.9, 0.75])))
    W(ul_close())

    # Windranger
    W(hero_header("Windranger"))
    W(ul_open())
    W(li("Agility gain increased from 1.7 to 1.9", b(1.7, 1.9)))
    W(ul_close())
    W(ability("Shackleshot", slug="windrunner_shackleshot"))
    W(ul_open())
    W(li("Shackle Duration increased from 1.6/2.1/2.6/3.1s to 1.75/2.25/2.75/3.25s", b([1.6, 2.1, 2.6, 3.1], [1.75, 2.25, 2.75, 3.25])))
    W(ul_close())

    # Winter Wyvern
    W(hero_header("Winter Wyvern"))
    W(facet_header("winter_wyvern_recursive"))
    W(ul_open())
    W(li("Winter's Curse: No longer amplifies physical, magical, and pure damage taken from Winter Wyvern", t("DEL")))
    W(ul_close())
    W(ability("Winter's Curse", slug="winter_wyvern_winters_curse"))
    W(ul_open())
    W(li("Cooldown increased from 85/80/75s to 100/90/80s", b([85, 80, 75], [100, 90, 80], l=True)))
    W(li("Cursed target is no longer immune to physical damage from Winter Wyvern and her controlled units", t("MISC")))
    W(ul_close())

    # Zeus
    W(hero_header("Zeus"))
    W(ul_open())
    W(li("Base damage decreased by 4", bstat_h("Zeus", "AttackDamageMin", "7.38", -4), extra=note_box(hero="Zeus", field="AttackDamageMin", before_patch="7.38")))
    W(li("Damage at level 1 decreased by 4 (from 55-63 to 51-59)", br(55, 63, 51, 59)))
    W(ul_close())
    W(ability("Lightning Bolt", slug="zuus_lightning_bolt"))
    W(ul_open())
    W(li("Sight Radius decreased from 750 to 500", b(750, 500)))
    W(ul_close())

    write_footer()
    save_html('patches/7.38b.html')
