from patch.api import *

_NC_CDN = "../icons/units/npc_dota_neutral_"

def build():
    write_head("7.39e", "02.10.2025")

    # ===== GENERAL UPDATES =====
    W(section("General Updates"))

    W(plain_header("General Changes"))
    W(ul_open())
    W(li("Scan no longer triggers on creep heroes (with the exception of Lone Druid's Spirit Bear)", t("MISC")))
    W(li("Neutral Creep Gold/XP penalty for stacked camps increased from 15% to 20%", b(15, 20, l=True)))
    W(ul_close())

    # ===== NEUTRAL CREEP UPDATES =====
    W(section("Neutral Creep Updates"))

    W(unit_header("Alpha Wolf", _NC_CDN + "alpha_wolf.png"))
    W(ability("Packleader's Aura", icon_url="../icons/abilities/alpha_wolf_command_aura.png", innate=False))
    W(ul_open())
    W(li("Damage decreased from 30% to 20%", b(30, 20)))
    W(ul_close())

    W(unit_header("Dark Troll Summoner", "../icons/units/npc_dota_neutral_dark_troll_warlord.png"))
    W(ability("Raise Dead", icon_url="../icons/abilities/dark_troll_warlord_raise_dead.png", innate=False))
    W(ul_open())
    W(li("Skeleton Warrior: Rally aura bonus attack damage decreased from 3 to 2", b(3, 2), also_dyn="unit|skeleton-warrior"))
    W(ul_close())

    # ===== ITEM UPDATES =====
    W(section("Item Updates"))

    W(item_header("Aeon Disk"))
    W(ul_open())
    W(li("Combo Breaker now starts on a 6s cooldown after being assembled for the first time", t("MISC")))
    W(ul_close())

    W(item_header("Ghost Scepter"))
    W(ul_open())
    W(li("Ghost Form is no longer active while the wearer is Debuff Immune", t("DEL")))
    W(ul_close())

    W(item_header("Ethereal Blade"))
    W(ul_open())
    W(li("Ether Blast ethereal form is no longer applied while the target is Debuff Immune", t("DEL")))
    W(ul_close())

    W(item_header("Helm of the Dominator"))
    W(ul_open())
    W(li("Dominate now has a 50 mana cost", b(0, 50, l=True)))
    W(li("Dominate can no longer be used if the currently dominated creep took damage from hero-based sources in the last 3s", t("DEL")))
    W(li("Dominated Creep movement speed decreased from 380 to 370", b(380, 370)))
    W(ul_close())

    W(item_header("Helm of the Overlord"))
    W(ul_open())
    W(li("Dominate now has a 50 mana cost", b(0, 50, l=True)))
    W(li("Dominate can no longer be used if the currently dominated creep took damage from hero-based sources in the last 3s", t("DEL")))
    W(ul_close())

    W(item_header("Refresher Orb"))
    W(ul_open())
    W(li("Reset Cooldowns cooldown now increases by 10s with each subsequent use up to 210s",
         t("NERF") + b(180, [180, 190, 200, 210], l=True),
         extra=inline_note("Maximum is reached after 4 uses: 180/190/200/210s")))
    W(li("Reset Cooldowns mana cost increased from 350 to 400", b(350, 400, l=True)))
    W(ul_close())

    # ===== NEUTRAL ITEM UPDATES =====
    W(section("Neutral Item Updates"))

    W(plain_header("Artifact Changes", dynamics=False, sublabel=True))
    W(item_header("Outworld Staff"))
    W(ul_open())
    W(li("Self-Exile now makes the user invulnerable and immobile for the duration, instead of hidden", t("REWORK")))
    W(ul_close())

    W(plain_header("Enchantment Changes", dynamics=False, sublabel=True))
    W(item_header("Timeless"))
    W(ul_open())
    W(li("Debuff Duration bonus decreased from +10/15% to +8/15%", b([10, 15], [8, 15])))
    W(li("Spell Amplification bonus decreased from +8/16% to +6/16%", b([8, 16], [6, 16])))
    W(ul_close())
    W(item_header("Boundless"))
    W(ul_open())
    W(li("Cast Range bonus decreased from +350 to +275", b(350, 275)))
    W(ul_close())

    # ===== HERO UPDATES =====
    W(section("Hero Updates"))

    W(hero_header("Abaddon"))
    W(ability("Borrowed Time", slug="abaddon_borrowed_time"))
    W(ul_open())
    W(li("Cooldown increased from 90/80/70s to 90/85/80s", b([90, 80, 70], [90, 85, 80], l=True)))
    W(ul_close())

    W(hero_header("Bane"))
    W(ability("Enfeeble", slug="bane_enfeeble"))
    W(ul_open())
    W(li("Cast Range decreased from 800/900/1000/1100 to 700/800/900/1000", b([800, 900, 1000, 1100], [700, 800, 900, 1000])))
    W(ul_close())

    W(hero_header("Beastmaster"))
    W(ul_open())
    W(li("Base damage decreased by 2", bstat_h("Beastmaster", "AttackDamageMin", "7.39e", -2), extra=note_box(hero="Beastmaster", field="AttackDamageMin", before_patch="7.39e")))
    W(li("Damage at level 1 decreased from 52–56 to 50–54", t("NERF")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Movespeed to Beastmaster and his summons decreased from +20 to +15", b(20, 15)))
    W(li("Level 25 Talent Primal Roar Cooldown Reduction decreased from 30s to 25s", b(30, 25)))
    W(ul_close())

    W(hero_header("Brewmaster"))
    W(ul_open())
    W(li("Base armor increased by 1", bstat_h("Brewmaster", "ArmorPhysical", "7.39e", 1), extra=note_box(hero="Brewmaster", field="ArmorPhysical", before_patch="7.39e")))
    W(ul_close())

    W(hero_header("Centaur Warrunner"))
    W(ability("Work Horse", slug="centaur_work_horse"))
    W(ul_open())
    W(li("Hitch a Ride cast range decreased from 300 to 250", b(300, 250)))
    W(ul_close())

    W(hero_header("Crystal Maiden"))
    W(facet_header("crystal_maiden_arcane_overflow"))
    W(ul_open())
    W(li("Freezing Field: Mana Granted increased from 15% to 20%", b(15, 20)))
    W(ul_close())

    W(hero_header("Dawnbreaker"))
    W(ability("Solar Guardian", slug="dawnbreaker_solar_guardian"))
    W(ul_open())
    W(li("Aghanim's Scepter aura linger duration decreased from 3s to 2s", b(3, 2)))
    W(ul_close())

    W(hero_header("Disruptor"))
    W(facet_header("disruptor_thunderstorm"))
    W(ul_open())
    W(li("Static Storm: Slow duration bonus decreased from +100% to +75%", b(100, 75),
         extra=inline_note("Total duration decreased from 0.6s to 0.525s")))
    W(ul_close())
    W(ul_open())
    W(li("Static Storm: Cooldown increased from 90/80/70s to 100/85/70s", b([90, 80, 70], [100, 85, 70], l=True)))
    W(ul_close())

    W(hero_header("Earth Spirit"))
    W(ability("Geomagnetic Grip", slug="earth_spirit_geomagnetic_grip"))
    W(ul_open())
    W(li("Remnant Damage increased from 70/140/210/280 to 75/150/225/300", b([70, 140, 210, 280], [75, 150, 225, 300])))
    W(ul_close())

    W(hero_header("Earthshaker"))
    W(facet_header("earthshaker_tectonic_buildup"))
    W(ul_open())
    W(li("Fissure: Bonus AoE decreased from 40 to 30", b(40, 30)))
    W(ul_close())
    W(ul_open())
    W(li("Aftershock: Damage decreased from 70/100/130/160 to 65/90/115/140", b([70, 100, 130, 160], [65, 90, 115, 140])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Fissure Damage decreased from +90 to +75", b(90, 75)))
    W(ul_close())

    W(hero_header("Hoodwink"))
    W(ability("Hunter's Boomerang", slug="hoodwink_hunters_boomerang"))
    W(ul_open())
    W(li("Incoming Spell Damage Amp decreased from 25% to 20%", b(25, 20)))
    W(ul_close())

    W(hero_header("Jakiro"))
    W(ability("Liquid Frost", slug="jakiro_liquid_ice"))
    W(ul_open())
    W(li("Impact Damage increased from 10/15/20/25 to 15/20/25/30", b([10, 15, 20, 25], [15, 20, 25, 30])))
    W(li("Duration increased from 4s to 5s", b(4, 5)))
    W(ul_close())

    W(hero_header("Kez"))
    W(ul_open())
    W(li("Added to Captain's Mode", t("NEW")))
    W(li("Base Mana Regen increased from 0 to 0.25", b(0, 0.25)))
    W(ul_close())
    W(facet_header("kez_flutter"))
    W(ul_open())
    W(li("Switch Discipline: The first hit bonus is now consumed by the first attack of Echo Slash and Raptor Dance, rather than applying to the entire cast", t("MISC"),
         extra=inline_note("Still applies bonus to all enemies in the area")))
    W(li("Switch Discipline: Fixed the Katana bonus being lost if Echo Slash hit nothing", t("MISC")))
    W(ul_close())
    W(ul_open())
    W(li("Switch Discipline: Fixed a bug with Aghanim's Scepter that would allow extra Sai abilities to skip cooldown", t("MISC")))
    W(ul_close())
    W(ul_open())
    W(li("Kazurai Katana: Impale damage changed from post-critical strike bonus damage to a separate instance of physical spell damage", t("REWORK")))
    W(ul_close())
    W(ul_open())
    W(li("Raptor Dance: Max Health as Damage decreased from 3% to 2.5%", b(3, 2.5)))
    W(li("Can no longer be interrupted by casting Grappling Claw", t("MISC")))
    W(ul_close())
    W(ul_open())
    W(li("Falcon Rush: Now has an 825 break distance", t("NEW")))
    W(li("Attack Speed Factor rescaled from 6/8/10/12% to 9%", b([6, 8, 10, 12], 9)))
    W(ul_close())
    W(ul_open())
    W(li("Shodo Sai: Mark Critical Strike decreased from 140/160/180/200% to 125/150/175/200%", b([140, 160, 180, 200], [125, 150, 175, 200])))
    W(ul_close())

    W(hero_header("Leshrac"))
    W(ability("Nihilism", slug="leshrac_greater_lightning_storm"))
    W(ul_open())
    W(li("Ethereal form is not applied if the target is Debuff Immune", t("DEL")))
    W(ul_close())

    W(hero_header("Lich"))
    W(ul_open())
    W(li("Base Intelligence increased from 26 to 28", b(26, 28)))
    W(li("Damage at level 1 increased by 2 (from 50–59 to 52–61)", t("BUFF")))
    W(ul_close())

    W(hero_header("Lifestealer"))
    W(ability("Feast", slug="life_stealer_feast"))
    W(ul_open())
    W(li("Hero Creeps no longer count as heroes for Lifestealer's permanent Health bonus", t("DEL")))
    W(ul_close())

    W(hero_header("Lina"))
    W(ability("Light Strike Array", slug="lina_light_strike_array"))
    W(ul_open())
    W(li("Stun Duration increased from 1/1.4/1.8/2.2s to 1.2/1.6/2.0/2.4s", b([1, 1.4, 1.8, 2.2], [1.2, 1.6, 2, 2.4])))
    W(ul_close())

    W(hero_header("Magnus"))
    W(ability("Skewer", slug="magnataur_skewer"))
    W(ul_open())
    W(li("Movement is now cancelled if Magnus is interrupted", t("REWORK"),
         extra=inline_note("Stunned, hexed or out of world")))
    W(ul_close())

    W(hero_header("Marci"))
    W(ability("Unleash", slug="marci_unleash"))
    W(ul_open())
    W(li("Bonus Attack Speed decreased from 700/975/1325 to 700/925/1150", b([700, 975, 1325], [700, 925, 1150])))
    W(ul_close())

    W(hero_header("Mars"))
    W(ability("Arena Of Blood", slug="mars_arena_of_blood"))
    W(ul_open())
    W(li("Duration rescaled from 5/6/7s to 5.5s", b([5, 6, 7], 5.5)))
    W(ul_close())

    W(hero_header("Medusa"))
    W(ability("Mana Shield", slug="medusa_mana_shield"))
    W(ul_open())
    W(li("Base Damage per Mana decreased from 2.2 to 2.0", b(2.2, 2.0)))
    W(ul_close())

    W(hero_header("Monkey King"))
    W(ability("Boundless Strike", slug="monkey_king_boundless_strike"))
    W(ul_open())
    W(li("Aghanim's Shard portion of Primal Spring's max power decreased from 40% to 35%", b(40, 35)))
    W(ul_close())
    W(ability("Tree Dance", slug="monkey_king_tree_dance"))
    W(ul_open())
    W(li("Movement is now cancelled if Monkey King is interrupted", t("REWORK"),
         extra=inline_note("Stunned, hexed or out of world")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Primal Spring Max Damage decreased from +100 to +85", b(100, 85)))
    W(ul_close())

    W(hero_header("Naga Siren"))
    W(facet_header("naga_siren_active_riptide"))
    W(ul_open())
    W(li("Rip Tide: Damage decreased from 80/150/220/290 to 80/140/200/260", b([80, 150, 220, 290], [80, 140, 200, 260])))
    W(ul_close())
    W(ul_open())
    W(li("Song of the Siren: Aghanim's Shard Max HP Regen per Second decreased from 5/6/7% to 4/5/6%", b([5, 6, 7], [4, 5, 6]),
         extra=inline_note("Aghanim's Shard bonus decreased from +3% to +2% — " + b(3, 2))))
    W(ul_close())

    W(hero_header("Necrophos"))
    W(ability("Ghost Shroud", slug="necrolyte_ghost_shroud"))
    W(ul_open())
    W(li("Ethereal form is not applied if the target is Debuff Immune", t("DEL")))
    W(ul_close())

    W(hero_header("Omniknight"))
    W(ability("Purification", slug="omniknight_purification"))
    W(ul_open())
    W(li("Cast Range increased from 600 to 700", b(600, 700)))
    W(ul_close())

    W(hero_header("Outworld Destroyer"))
    W(ability("Arcane Orb", slug="obsidian_destroyer_arcane_orb"))
    W(ul_open())
    W(li("Cooldown decreased from 6/4/2/0s to 4.5/3/1.5/0s", b([6, 4, 2, 0], [4.5, 3, 1.5, 0], l=True)))
    W(ul_close())

    W(hero_header("Phantom Assassin"))
    W(ability("Immaterial", slug="phantom_assassin_immaterial"))
    W(ul_open())
    W(li("Bonus Evasion increased from 20/30/40/50% to 25/35/45/55%", b([20, 30, 40, 50], [25, 35, 45, 55])))
    W(ul_close())

    W(hero_header("Phoenix"))
    W(ability("Supernova", slug="phoenix_supernova"))
    W(ul_open())
    W(li("Aghanim's Scepter cast range decreased from 500 to 450", b(500, 450)))
    W(ul_close())

    W(hero_header("Puck"))
    W(facet_header("puck_curveball"))
    W(ul_open())
    W(li("Illusory Orb: Bonus damage per tick decreased from 5% to 3%", b(5, 3)))
    W(ul_close())

    W(hero_header("Pugna"))
    W(facet_header("pugna_siphoning_ward"))
    W(ul_open())
    W(li("Nether Ward: Damage to HP decreased from 30% to 25%", b(30, 25)))
    W(li("Nether Ward: Damage to Mana decreased from 40% to 30%", b(40, 30)))
    W(ul_close())
    W(ul_open())
    W(li("Decrepify: Ethereal form is not applied if the target is Debuff Immune", t("DEL")))
    W(ul_close())

    W(hero_header("Queen of Pain"))
    W(ability("Sonic Wave", slug="queenofpain_sonic_wave"))
    W(ul_open())
    W(li("Damage decreased from 350/500/650 to 325/475/625", b([350, 500, 650], [325, 475, 625])))
    W(ul_close())

    W(hero_header("Razor"))
    W(ability("Static Link", slug="razor_static_link"))
    W(ul_open())
    W(li("Cooldown decreased from 50/40/30/20s to 44/36/28/20s", b([50, 40, 30, 20], [44, 36, 28, 20], l=True)))
    W(ul_close())

    W(hero_header("Riki"))
    W(ability("Blink Strike", slug="riki_blink_strike"))
    W(ul_open())
    W(li("Slow Duration increased from 0.4s to 0.5s", b(0.4, 0.5)))
    W(ul_close())

    W(hero_header("Ringmaster"))
    W(ability("Tame the Beasts", slug="ringmaster_tame_the_beasts"))
    W(ul_open())
    W(li("Min Damage increased from 45/70/95/120 to 50/75/100/125", b([45, 70, 95, 120], [50, 75, 100, 125])))
    W(ul_close())

    W(hero_header("Rubick"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Telekinesis Landing damage increased from 150 to 165", b(150, 165)))
    W(ul_close())

    W(hero_header("Sand King"))
    W(facet_header("sand_king_obscurity"))
    W(ul_open())
    W(li("Sand Storm: Blind debuff no longer affects buildings", t("DEL")))
    W(ul_close())

    W(hero_header("Silencer"))
    W(ability("Arcane Curse", slug="silencer_curse_of_the_silent"))
    W(ul_open())
    W(li("Cast Range decreased from 1000 to 850", b(1000, 850)))
    W(ul_close())

    W(hero_header("Snapfire"))
    W(facet_header("snapfire_full_bore"))
    W(ul_open())
    W(li("Scatterblast: Max range decreased from 1300 to 1200", b(1300, 1200),
         extra=inline_note("Point-blank distance is not changed. It is still 650")))
    W(ul_close())
    W(ul_open())
    W(li("Firesnap Cookie: Cast Range decreased from 700 to 650", b(700, 650)))
    W(ul_close())

    W(hero_header("Storm Spirit"))
    W(ability("Overload", slug="storm_spirit_overload"))
    W(ul_open())
    W(li("Aghanim's Shard active mana cost decreased from 150 to 100", b(150, 100, l=True)))
    W(ul_close())

    W(hero_header("Sven"))
    W(ability("Wrath of God", slug="sven_wrath_of_god"))
    W(ul_open())
    W(li("Bonus Damage per STR decreased from 0/0.3/0.4/0.5 to 0/0.2/0.3/0.4", b([0, 0.3, 0.4, 0.5], [0, 0.2, 0.3, 0.4])))
    W(ul_close())

    W(hero_header("Techies"))
    W(ability("Reactive Tazer", slug="techies_reactive_tazer"))
    W(ul_open())
    W(li("Cooldown decreased from 30/25/20/15s to 26/22/18/14s", b([30, 25, 20, 15], [26, 22, 18, 14], l=True)))
    W(ul_close())
    W(ability("Proximity Mines", slug="techies_land_mines"))
    W(ul_open())
    W(li("Min damage at the edge increased from 50% to 60%", b(50, 60)))
    W(ul_close())

    W(hero_header("Timbersaw"))
    W(ability("Reactive Armor", slug="shredder_reactive_armor"))
    W(ul_open())
    W(li("Stacks gained from hero attacks increased from 3 to 4", b(3, 4)))
    W(ul_close())

    W(hero_header("Treant Protector"))
    W(ul_open())
    W(li("Base armor increased by 1", bstat_h("Treant Protector", "ArmorPhysical", "7.39d", 1), extra=note_box(hero="Treant Protector", field="ArmorPhysical", before_patch="7.39d")))
    W(ul_close())
    W(ability("Living Armor", slug="treant_living_armor"))
    W(ul_open())
    W(li("Bonus Armor increased from 4/6/8/10 to 4/7/10/13", b([4, 6, 8, 10], [4, 7, 10, 13])))
    W(ul_close())

    W(hero_header("Troll Warlord"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Berserker's Rage Movement Speed decreased from +25 to +20", b(25, 20)))
    W(li("Level 15 Talent Fervor Attack Speed decreased from +5 to +4", b(5, 4)))
    W(ul_close())

    W(hero_header("Tusk"))
    W(ability("Bitter Chill", slug="tusk_bitter_chill"))
    W(ul_open())
    W(li("Attack Speed Slow increased from 15/35/55/75 to 20/40/60/80", b([15, 35, 55, 75], [20, 40, 60, 80])))
    W(ul_close())

    W(hero_header("Ursa"))
    W(ability("Earthshock", slug="ursa_earthshock"))
    W(ul_open())
    W(li("Aghanim's Shard Enrage duration decreased from 1.3s to 1.2s", b(1.3, 1.2)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Fury Swipes Reset Time decreased from +12s to +9s", b(12, 9)))
    W(ul_close())

    W(hero_header("Venomancer"))
    W(ul_open())
    W(li("Base agility increased from 24 to 25", b(24, 25)))
    W(li("Damage at level 1 increased by 1 (from 45–48 to 46–49)", t("BUFF")))
    W(ul_close())
    W(ability("Plague Ward", slug="venomancer_plague_ward"))
    W(ul_open())
    W(li("Ward damage increased from 14/22/30/38 to 16/24/32/40", b([14, 22, 30, 38], [16, 24, 32, 40])))
    W(ul_close())

    W(hero_header("Viper"))
    W(ability("Corrosive Skin", slug="viper_corrosive_skin"))
    W(ul_open())
    W(li("Attack Slow increased from 8/16/24/32 to 9/18/27/36", b([8, 16, 24, 32], [9, 18, 27, 36])))
    W(ul_close())

    W(hero_header("Visage"))
    W(ability("Grave Chill", slug="visage_grave_chill"))
    W(ul_open())
    W(li("Mana Cost decreased from 90 to 75", b(90, 75, l=True)))
    W(ul_close())

    write_footer()
    save_html('patches/7.39e.html')
