from patch.api import *

def build():
    write_head("7.41b", "07.04.2026")

    # ===== GENERAL UPDATES =====
    W(section("General Updates"))

    W(plain_header("Map Objectives"))
    W(subgroup("Tormentor"))
    W(ul_open())
    W(li("Reflect Damage reflection per minute decreased from 2% to 1.5%", b(2, 1.5)))
    W(ul_close())

    # ===== NEUTRAL CREEP UPDATES =====
    W(section("Neutral Creep Updates"))
    W(unit_header("Frostbitten Golem", "../icons/units/npc_dota_neutral_frostbitten_golem.png"))
    W(ability("Time Warp Aura", icon_url="../icons/abilities/frostbitten_golem_time_warp_aura.png"))
    W(ul_open())
    W(li("Cooldown Reduction decreased from 10/11/12/14% to 8/9/10/11%", b([10, 11, 12, 14], [8, 9, 10, 11], l=True)))
    W(ul_close())

    # ===== ITEM UPDATES =====
    W(section("Item Updates"))

    W(item_header("Black King Bar"))
    W(ul_open())
    W(li("Avatar now has a fixed duration and is not affected by buff duration amplification", t("NERF")))
    W(ul_close())
    W(item_header("Consecrated Wraps"))
    W(ul_open())
    W(li("All Attributes bonus decreased from +6 to +5", b(6, 5)))
    W(li("Hallowed stacks are now item charges instead of a stack counter on the buff", t("REWORK")))
    W(li("All charges are consumed when the barrier is created", t("NERF")))
    W(li("Charge Restore Time of Hallowed is not affected by effects that reduce or modify cooldowns", t("NERF")))
    W(li("Hallowed now starts with all 3 charges when Consecrated Wraps is purchased or built", t("MISC")))
    W(li("Gaining max stacks requirement for the speedup buff is removed", t("BUFF")))
    W(li("Initial 3 charges don't provide the movement speed buff", t("MISC")))
    W(li("Hallowed charge gain time increased from 3s to 4s", b(3, 4)))
    W(ul_close())
    W(item_header("Gleipnir"))
    W(ul_open())
    W(li("Eternal Chains radius increased from 275 to 325", b(275, 325)))
    W(li("Effective radius increased from 350 to 400 due to item's built-in Area of Effect bonus", b(350, 400)))
    W(ul_close())
    W(item_header("Heaven's Halberd"))
    W(ul_open())
    W(li("Health Regen bonus increased from +6 to +6.5", b(6, 6.5)))
    W(ul_close())
    W(item_header("Helm of the Overlord"))
    W(ul_open())
    W(li("Dominate cooldown decreased from 45s to 40s", b(45, 40, l=True)))
    W(li("Dominate target unit's max health minimum increased from 1800 to 1900", b(1800, 1900, l=True)))
    W(ul_close())
    W(item_header("Holy Locket"))
    W(ul_open())
    W(li("Energy Charge incoming Heal Amplification increased from 10% to 15%", b(10, 15)))
    W(li("Holy Blessing outgoing Heal Amplification decreased from 15% to 10%", b(15, 10)))
    W(ul_close())
    W(item_header("Mage Slayer"))
    W(ul_open())
    W(li("Health Regen bonus decreased from +6 to +5.5", b(6, 5.5)))
    W(li("Magic Resistance bonus decreased from 20% to 18%", b(20, 18)))
    W(ul_close())
    W(item_header("Sange"))
    W(ul_open())
    W(li("Health Restoration bonus decreased from 16% to 12%", b(16, 12)))
    W(ul_close())
    W(item_header("Abyssal Blade"))
    W(ul_open())
    W(li("Health Restoration bonus decreased from 20% to 16%", b(20, 16)))
    W(ul_close())
    W(item_header("Sange and Yasha"))
    W(ul_open())
    W(li("Health Restoration bonus decreased from 20% to 16%", b(20, 16)))
    W(ul_close())
    W(item_header("Kaya and Sange"))
    W(ul_open())
    W(li("Health Restoration bonus decreased from 20% to 16%", b(20, 16)))
    W(ul_close())
    # ===== NEUTRAL ITEM UPDATES =====
    W(section("Neutral Item Updates"))
    W(plain_header("Artifact changes", dynamics=False))
    W(item_header("Jidi Pollen Bag"))
    W(ul_open())
    W(li("Pollinate radius increased from 700 to 900", b(700, 900)))
    W(ul_close())
    W(item_header("Conjurer's Catalyst"))
    W(ul_open())
    W(li("Spellover now has a 0.1s internal cooldown", t("REWORK")))
    W(ul_close())
    W(subnote("Still can proc multiple times from a single instance of high damage"))
    W(ul_open())
    W(li("Spellover damage threshold increased from 100 to 200", b(100, 200)))
    W(li("Spellover damage from hero targets increased from 40 to 80", b(40, 80)))
    W(ul_close())
    W(subnote("From 52 to 104 with Dormant Curio"))
    W(ul_open())
    W(li("Spellover damage from creep targets increased from 15 to 30", b(15, 30)))
    W(ul_close())
    W(subnote("From 19.5 to 39 with Dormant Curio"))
    W(item_header("Enchanter's Bauble"))
    W(ul_open())
    W(li("Enchant base Neutral Enchantment bonus decreased from 15% to 10%", b(15, 10)))
    W(ul_close())
    W(item_header("Idol of Scree'auk"))
    W(ul_open())
    W(li("False Flight duration increased from 5s to 6.5s", b(5, 6.5)))
    W(ul_close())
    W(subnote("From 6.5s to 8.45s with Dormant Curio"))
    W(item_header("Metamorphic Mandible"))
    W(ul_open())
    W(li("Pupate movement speed bonus increased from 15% to 20%", b(15, 20)))
    W(ul_close())
    W(item_header("Rattlecage"))
    W(ul_open())
    W(li("Reverberate projectile physical damage decreased from 110 to 90", b(110, 90)))
    W(ul_close())
    W(subnote("From 143 to 117 with Dormant Curio"))
    W(item_header("Book of the Dead"))
    W(ul_open())
    W(li("Demonic Warrior no longer has True Sight ability", t("DEL")))
    W(ul_close())
    W(item_header("Minotaur Horn"))
    W(ul_open())
    W(li("Lesser Avatar bonus magic resistance increased from 50% to 60%", b(50, 60)))
    W(ul_close())
    W(item_header("Riftshadow Prism"))
    W(ul_open())
    W(li("Refract cooldown decreased from 30s to 27s", b(30, 27, l=True)))
    W(ul_close())
    W(plain_header("Enchantment changes", dynamics=False))
    W(enchant_header("Crude", "crude"))
    W(ul_open())
    W(li("Health Restoration bonus decreased from +10/15/20% to +9/12/15%", b([10, 15, 20], [9, 12, 15])))
    W(ul_close())

    # ===== HERO UPDATES =====
    W(section("Hero Updates"))


    # Alchemist
    W(hero_header("Alchemist"))
    W(ul_open())
    W(li("Base Agility decreased from 22 to 19", b(22, 19)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent +1 Acid Spray Armor Reduction replaced with +1% Corrosive Weaponry Slow / Damage Reduction Per Stack", t("REWORK")))
    W(li("Level 15 Talent +1% Corrosive Weaponry Slow / Damage Reduction Per Stack replaced with +1 Acid Spray Armor Reduction", t("REWORK")))
    W(ul_close())

    # Ancient Apparition
    W(hero_header("Ancient Apparition"))
    W(ability("Bone Chill"))
    W(ul_open())
    W(li("Aghanim's Scepter Strength Reduction bonus increased from 0.3 to 0.8", b(0.3, 0.8)))
    W(ul_close())

    # Anti-Mage
    W(hero_header("Anti-Mage"))
    W(ability("Mana Break"))
    W(ul_open())
    W(li("Max Mana Burned per hit increased from 1.6/2.4/3.2/4% to 1.8/2.7/3.6/4.5%", b([1.6, 2.4, 3.2, 4], [1.8, 2.7, 3.6, 4.5])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Blink Cast Range decreased from +150 to +125", b(150, 125)))
    W(ul_close())

    # Arc Warden
    W(hero_header("Arc Warden"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Magnetic Field Cooldown Reduction decreased from 5s to 4s", b(5, 4, l=True)))
    W(li("Level 20 Talent +200 Spark Wraith Damage replaced with +30s Spark Wraith Duration", t("REWORK")))
    W(li("Level 25 Talent +30s Spark Wraith Duration replaced with +240 Spark Wraith Damage", t("REWORK")))
    W(li("Level 25 Talent Runic Infusion All Attributes Bonus decreased from +1.5 to +1", b(1.5, 1)))
    W(ul_close())

    # Batrider
    W(hero_header("Batrider"))
    W(ul_open())
    W(li("Base Armor decreased by 1", bstat_h("Batrider", "ArmorPhysical", "7.41a", -1), extra=note_box(hero="Batrider", field="ArmorPhysical", before_patch="7.41a")))
    W(ul_close())
    W(ability("Firefly"))
    W(ul_open())
    W(li("Cooldown increased from 45/40/35/30s to 48/42/36/30s", b([45, 40, 35, 30], [48, 42, 36, 30], l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Sticky Napalm Movement Slow increased from +0.5% to +0.75%", b(0.5, 0.75)))
    W(ul_close())

    # Beastmaster
    W(hero_header("Beastmaster"))
    W(ul_open())
    W(li("Base Attack Speed decreased from 100 to 90", b(100, 90)))
    W(ul_close())
    W(ability("Wild Axes"))
    W(ul_open())
    W(li("Debuff Duration rescaled from 12s to 10/11/12/13s", b(12, [10, 11, 12, 13])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Armor decreased from +5 to +4", b(5, 4)))
    W(li("Level 10 Talent Wild Axes Damage Amp Per Stack decreased from +2% to +1.5%", b(2, 1.5)))
    W(ul_close())

    # Bloodseeker
    W(hero_header("Bloodseeker"))
    W(ability("Rupture"))
    W(ul_open())
    W(li("Mana Cost increased from 100/150/200 to 125/175/225", b([100, 150, 200], [125, 175, 225], l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25 Talent Max Thirst Move Speed decreased from +18% to +15%", b(18, 15)))
    W(ul_close())

    # Broodmother
    W(hero_header("Broodmother"))
    W(ul_open())
    W(li("Base agility increased from 18 to 20", b(18, 20)))
    W(li("Damage at level 1 increased from 45-51 to 47-53", br(45, 51, 47, 53)))
    W(ul_close())

    # Chaos Knight
    W(hero_header("Chaos Knight"))
    W(ability("Phantasm"))
    W(ul_open())
    W(li("Cooldown increased from 75s to 85/80/75s", b(75, [85, 80, 75], l=True)))
    W(li("Number of Phantasms increased from 1/2/3 to 3", b([1, 2, 3], 3)))
    W(li("Phantasm Damage decreased from 100% to 50/75/100%", b(100, [50, 75, 100])))
    W(ul_close())

    # Chen
    W(hero_header("Chen"))
    W(ability("Holy Persuasion"))
    W(ul_open())
    W(li("Bonus Damage increased from 0/6/12/18% to 5/10/15/20%", b([0, 6, 12, 18], [5, 10, 15, 20])))
    W(ul_close())

    # Clinkz
    W(hero_header("Clinkz"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Strafe Duration increased from +0.75s to +1s", b(0.75, 1)))
    W(ul_close())

    # Crystal Maiden
    W(hero_header("Crystal Maiden"))
    W(ability("Crystal Clone"))
    W(ul_open())
    W(li("Cooldown increased from 10s to 12s", b(10, 12, l=True)))
    W(ul_close())

    # Dawnbreaker
    W(hero_header("Dawnbreaker"))
    W(ability("Break of Dawn"))
    W(ul_open())
    W(li_formula("Max Damage Increase decreased", "10% + 1% per level", "8% + 1% per level", lambda L: 10.0 + 1.0*L, lambda L: 8.0 + 1.0*L))
    W(ul_close())

    # Death Prophet
    W(hero_header("Death Prophet"))
    W(ability("Exorcism"))
    W(ul_open())
    W(li("Spirit Damage increased from 64 to 65/68/71", b(64, [65, 68, 71])))
    W(ul_close())
    W(subnote("From 62-67 to 62-68/65-71/68-74"))

    # Doom
    W(hero_header("Doom"))
    W(ability("Scorched Earth"))
    W(ul_open())
    W(li("Damage decreased from 20/35/50/65 to 20/30/40/50", b([20, 35, 50, 65], [20, 30, 40, 50])))
    W(ul_close())
    W(ability("Doom"))
    W(ul_open())
    W(li("Damage per second decreased from 25/45/66 to 22/44/66", b([25, 45, 66], [22, 44, 66])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Devour grants 15% Magic Resistance replaced with +10% Magic Resistance", t("REWORK")))
    W(li("Level 15 Talent +66 Damage replaced with +1.5% Infernal Blade Max HP As Damage", t("REWORK")))
    W(li("Level 20 Talent +2.5% Infernal Blade Max HP As Damage replaced with +66 Damage", t("REWORK")))
    W(ul_close())

    # Drow Ranger
    W(hero_header("Drow Ranger"))
    W(ul_open())
    W(li("Base Agility increased from 22 to 24", b(22, 24)))
    W(li("Damage at level 1 increased from 49-56 to 51-58", br(49, 56, 51, 58)))
    W(ul_close())
    W(ability("Marksmanship"))
    W(ul_open())
    W(li("Enemy hero disable range decreased from 325 to 300", b(325, 300)))
    W(ul_close())
    W(ability("Glacier"))
    W(ul_open())
    W(li("While on the glacier, Marksmanship now can be disabled by enemies in the proximity", t("NERF")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25 Talent Multishot Waves increased from +1 to +2", b(1, 2)))
    W(ul_close())

    # Elder Titan
    W(hero_header("Elder Titan"))
    W(ability("Momentum"))
    W(ul_open())
    W(li_formula("Bonus Speed to Armor increased", "3.6% + 0.4% per level", "5.0% + 0.5% per level", lambda L: 3.6 + 0.4*L, lambda L: 5.0 + 0.5*L))
    W(ul_close())

    # Ember Spirit
    W(hero_header("Ember Spirit"))
    W(ul_open())
    W(li("Base Damage decreased by 3", bstat_h("Ember Spirit", "AttackDamageMin", "7.41a", -3), extra=note_box(hero="Ember Spirit", field="AttackDamageMin", before_patch="7.41a")))
    W(li("Damage at level 1 decreased from 55-59 to 52-56", br(55, 59, 52, 56)))
    W(ul_close())
    W(ability("Sleight of Fist"))
    W(ul_open())
    W(li("Mana Cost increased from 60/65/70/75 to 75", b([60, 65, 70, 75], 75, l=True)))
    W(ul_close())

    # Enigma
    W(hero_header("Enigma"))
    W(ability("Event Horizon"))
    W(ul_open())
    W(li_formula("Movement Slow increased", "4% + 1% per level", "5% + 1% per level", lambda L: 4.0 + 1.0*L, lambda L: 5.0 + 1.0*L))
    W(ul_close())
    W(ability("Demonic Summoning", slug="enigma_demonic_conversion"))
    W(ul_open())
    W(li("Fixed Eidolons not having an 8 attack damage spread", t("MISC")))
    W(li("Eidolon Damage increased from 16/27/38/49 to 16/28/40/52", b([16, 27, 38, 49], [16, 28, 40, 52]),
         extra=inline_note("As a result, damage changed from 16/27/38/49 to 12-20/24-32/36-44/48-56")))
    W(ul_close())

    # Gyrocopter
    W(hero_header("Gyrocopter"))
    W(ability("Flak Cannon"))
    W(ul_open())
    W(li("Cooldown rescaled from 26/24/22/20s to 25s", b([26, 24, 22, 20], 25, l=True)))
    W(ul_close())
    W(ability("Call Down"))
    W(ul_open())
    W(li("Cooldown decreased from 90/75/60s to 75/65/55s", b([90, 75, 60], [75, 65, 55], l=True)))
    W(ul_close())

    # Hoodwink
    W(hero_header("Hoodwink"))
    W(ability("Hunter's Boomerang"))
    W(ul_open())
    W(li("Debuff Duration decreased from 7s to 6s", b(7, 6)))
    W(ul_close())

    # Invoker
    W(hero_header("Invoker"))
    W(ability("Invoke"))
    W(ul_open())
    W(li("Now grants Invoker an additional Ability Point at hero levels 6, 12, and 18", t("NEW")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent +1 Orb Levels replaced with +50% Forged Spirit Armor Reduction", t("REWORK")))
    W(ul_close())

    # Jakiro
    W(hero_header("Jakiro"))
    W(ability("Dual Breath"))
    W(ul_open())
    W(li("Cooldown rescaled from 10s to 12/11/10/9s", b(10, [12, 11, 10, 9], l=True)))
    W(ul_close())
    W(ability("Liquid Fire"))
    W(ul_open())
    W(li("Burn Damage rescaled from 15/25/35/45 to 12/24/36/48", b([15, 25, 35, 45], [12, 24, 36, 48])))
    W(ul_close())
    W(ability("Macropyre"))
    W(ul_open())
    W(li("Mana Cost decreased from 300/400/500 to 250/350/450", b([300, 400, 500], [250, 350, 450], l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Macropyre Damage increased from +20 to +25", b(20, 25)))
    W(ul_close())

    # Juggernaut
    W(hero_header("Juggernaut"))
    W(ul_open())
    W(li("Base Movement Speed increased from 300 to 305", b(300, 305)))
    W(ul_close())
    W(ability("Bladeform"))
    W(ul_open())
    W(li_formula("Base Agility per stack increased", "2.5% + 0.05% per level", "2.5% + 0.1% per level", lambda L: 2.5 + 0.05*L, lambda L: 2.5 + 0.1*L))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Blade Fury Damage per second increased from +100 to +120", b(100, 120)))
    W(ul_close())

    # Keeper of the Light
    W(hero_header("Keeper of the Light"))
    W(ability("Bright Speed"))
    W(ul_open())
    W(li("Intelligence required for 1 movement speed increased from 2.5 to 3", b(2.5, 3, l=True)))
    W(ul_close())
    W(ability("Spirit Form"))
    W(ul_open())
    W(li("Cast Range Bonus decreased from 100/200/300 to 100/175/250", b([100, 200, 300], [100, 175, 250])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Spirit Form Bright Speed Bonus decreased from +30% to +25%", b(30, 25)))
    W(ul_close())

    # Largo
    W(hero_header("Largo"))
    W(ability("Encore"))
    W(ul_open())
    W(li_formula("Bonus Duration increased", "9% + 1% per level", "10% + 1% per level", lambda L: 9.0 + 1.0*L, lambda L: 10.0 + 1.0*L))
    W(ul_close())
    W(ability("Croak of Genius"))
    W(ul_open())
    W(li("Mana Cost rescaled from 25/35/45/55 to 40", b([25, 35, 45, 55], 40, l=True)))
    W(li("Duration increased from 12/18/24/30s to 15/20/25/30s", b([12, 18, 24, 30], [15, 20, 25, 30])))
    W(ul_close())
    W(ability("Bullbelly Blitz", slug="largo_song_fight_song"))
    W(ul_open())
    W(li("Aghanim's Scepter Damage per stack decreased from 6/12/18 to 6/10/14", b([6, 12, 18], [6, 10, 14])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Catchy Lick Damage increased from +170 to +200", b(170, 200)))
    W(ul_close())

    # Lycan
    W(hero_header("Lycan"))
    W(ability("Shapeshift"))
    W(ul_open())
    W(li("Cooldown decreased from 110/100/90s to 105/95/85s", b([110, 100, 90], [105, 95, 85], l=True)))
    W(ul_close())

    # Magnus
    W(hero_header("Magnus"))
    W(ul_open())
    W(li("Agility gain increased from 2.0 to 2.2", b(2.0, 2.2)))
    W(li("Damage gain per level increased from 3.2 to 3.3 as a result", b(3.2, 3.3)))
    W(ul_close())

    # Meepo
    W(hero_header("Meepo"))
    W(ul_open())
    W(li("Base Movement Speed decreased from 315 to 310", b(315, 310)))
    W(li("Strength gain decreased from 2.2 to 2.0", b(2.2, 2.0)))
    W(ul_close())
    W(ability("Ransack"))
    W(ul_open())
    W(li("Health Steal (Heroes) decreased from 9/12/15/18 to 7/10/13/16", b([9, 12, 15, 18], [7, 10, 13, 16])))
    W(ul_close())
    W(ability("Divided We Stand"))
    W(ul_open())
    W(li("Max Health and Max Mana bonuses from items are now penalized by the number of Meepos (like other item bonuses)", t("NERF")))
    W(li("No longer shares cooldowns of Town Portal Scrolls", t("BUFF")))
    W(ul_close())
    W(ability("MegaMeepo"))
    W(ul_open())
    W(li("Cooldown increased from 60s to 90s", b(60, 90, l=True)))
    W(li("Duration decreased from 25s to 20s", b(25, 20)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent +40 Poof Damage replaced with -1.5s Earthbind Cooldown", t("REWORK")))
    W(li("Level 15 Talent -2.5s Earthbind Cooldown replaced with +40 Poof Damage", t("REWORK")))
    W(li("Level 20 Talent Ransack Health Steal decreased from +7 to +6", b(7, 6)))
    W(ul_close())

    # Monkey King
    W(hero_header("Monkey King"))
    W(ability("Changing of the Guard", slug="monkey_king_transfiguration"))
    W(ul_open())
    W(li("Cooldown increased from 3s to 5s", b(3, 5, l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Tree Dance Cast Range decreased from +350 to +300", b(350, 300)))
    W(ul_close())

    # Naga Siren
    W(hero_header("Naga Siren"))
    W(ul_open())
    W(li("Base Attack Speed decreased from 110 to 100", b(110, 100)))
    W(ul_close())
    W(ability("Eelskin"))
    W(ul_open())
    W(li_formula("Evasion per Naga decreased", "4.9% + 0.1% per level", "4% + 0.1% per level", lambda L: 4.9 + 0.1*L, lambda L: 4.0 + 0.1*L))
    W(ul_close())

    # Nature's Prophet
    W(hero_header("Nature's Prophet"))
    W(ability("Wrath of Nature"))
    W(ul_open())
    W(li("Base Damage increased from 90/130/170 to 100/140/180", b([90, 130, 170], [100, 140, 180])))
    W(ul_close())

    # Necrophos
    W(hero_header("Necrophos"))
    W(ability("Death Seeker"))
    W(ul_open())
    W(li("Mana Cost increased from 125 to 160", b(125, 160, l=True)))
    W(ul_close())

    # Night Stalker
    W(hero_header("Night Stalker"))
    W(ul_open())
    W(li("Base Health Regen decreased by 1.25", bstat_h("Night Stalker", "StatusHealthRegen", "7.41a", -1.25), extra=note_box(hero="Night Stalker", field="StatusHealthRegen", before_patch="7.41a")))
    W(ul_close())

    # Nyx Assassin
    W(hero_header("Nyx Assassin"))
    W(ability("Vendetta"))
    W(ul_open())
    W(li("Duration decreased from 60s to 45/50/55s", b(60, [45, 50, 55])))
    W(ul_close())

    # Omniknight
    W(hero_header("Omniknight"))
    W(ability("Hammer of Purity"))
    W(ul_open())
    W(li("Damage to heal increased from 30% to 35%", b(30, 35)))
    W(ul_close())
    W(ability("Guardian Angel"))
    W(ul_open())
    W(li("Duration increased from 4/4.5/5s to 4/4.75/5.5s", b([4, 4.5, 5], [4, 4.75, 5.5])))
    W(li("Aghanim's Scepter Bonus Health Restoration decreased from 100% to 50%", b(100, 50)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Degen Aura Radius increased from +125 to +150", b(125, 150)))
    W(ul_close())

    # Pangolier
    W(hero_header("Pangolier"))
    W(ability("Lucky Shot"))
    W(ul_open())
    W(li("Attack Speed Reduction decreased from 40/80/120/160 to 35/70/105/140", b([40, 80, 120, 160], [35, 70, 105, 140])))
    W(ul_close())
    W(ability("Rolling Thunder", slug="pangolier_gyroshell"))
    W(ul_open())
    W(li("Total Attack Damage as Damage decreased from 100% to 80%", b(100, 80)))
    W(ul_close())

    # Phantom Assassin
    W(hero_header("Phantom Assassin"))
    W(ul_open())
    W(li("Strength gain increased from 2.0 to 2.2", b(2.0, 2.2)))
    W(ul_close())
    W(ability("Phantom Strike"))
    W(ul_open())
    W(li("Duration increased from 2.5s to 3s", b(2.5, 3)))
    W(li("Bonus Attack Speed rescaled from 100/130/160/190 to 80/120/160/200", b([100, 130, 160, 190], [80, 120, 160, 200])))
    W(ul_close())
    W(ability("Coup de Grace"))
    W(ul_open())
    W(li("Critical Damage increased from 200/300/400% to 200/325/450%", b([200, 300, 400], [200, 325, 450])))
    W(ul_close())

    # Phoenix
    W(hero_header("Phoenix"))
    W(ul_open())
    W(li("Base Attack Range decreased from 525 to 500", b(525, 500)))
    W(ul_close())
    W(ability("Sun Ray"))
    W(ul_open())
    W(li("Aghanim's Shard no longer slows affected enemies by 10%", t("NERF")))
    W(ul_close())

    # Primal Beast
    W(hero_header("Primal Beast"))
    W(ability("Pulverize"))
    W(ul_open())
    W(li("Cooldown increased from 40/35/30s to 45/40/35s", b([40, 35, 30], [45, 40, 35], l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Damage decreased from +30 to +25", b(30, 25)))
    W(ul_close())

    # Pudge
    W(hero_header("Pudge"))
    W(ability("Meat Shield", slug="pudge_flesh_heap"))
    W(ul_open())
    W(li("Strength gain per stack increased from 1.6 to 2.0", b(1.6, 2.0)))
    W(ul_close())

    # Rubick
    W(hero_header("Rubick"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Telekinesis Landing Damage decreased from 325 to 300", b(325, 300)))
    W(ul_close())

    # Sand King
    W(hero_header("Sand King"))
    W(ability("Epicenter", slug="sandking_epicenter"))
    W(ul_open())
    W(li("Attack Slow decreased from 50/55/60 to 30/40/50", b([50, 55, 60], [30, 40, 50])))
    W(li("Aghanim's Scepter Stinger damage decreased from 50% to 40%", b(50, 40)))
    W(ul_close())

    # Shadow Demon
    W(hero_header("Shadow Demon"))
    W(ability("Disruption"))
    W(ul_open())
    W(li("Illusion Duration decreased from 11/12/13/14s to 8/10/12/14s", b([11, 12, 13, 14], [8, 10, 12, 14])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Movement Speed decreased from +25 to +20", b(25, 20)))
    W(ul_close())

    # Shadow Shaman
    W(hero_header("Shadow Shaman"))
    W(ul_open())
    W(li("Intelligence gain decreased from 3.5 to 3.3", b(3.5, 3.3)))
    W(ul_close())

    # Silencer
    W(hero_header("Silencer"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Global Silence Cooldown Reduction decreased from 20s to 15s", b(20, 15, l=True)))
    W(ul_close())

    # Skywrath Mage
    W(hero_header("Skywrath Mage"))
    W(ul_open())
    W(li("Base Mana Regen increased by 0.25", bstat_h("Skywrath Mage", "StatusManaRegen", "7.41a", 0.25), extra=note_box(hero="Skywrath Mage", field="StatusManaRegen", before_patch="7.41a")))
    W(ul_close())

    # Slardar
    W(hero_header("Slardar"))
    W(ability("Guardian Sprint", slug="slardar_sprint"))
    W(ul_open())
    W(li("Cooldown increased from 29/25/21/17s to 33/28/23/18s", b([29, 25, 21, 17], [33, 28, 23, 18], l=True)))
    W(ul_close())

    # Slark
    W(hero_header("Slark"))
    W(ability("Essence Shift"))
    W(ul_open())
    W(li_formula("Duration decreased", "12.5s + 2.5s per level", "10s + 2.5s per level", lambda L: 12.5 + 2.5*L, lambda L: 10.0 + 2.5*L, l=False))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Essence Shift Duration decreased from +25s to +20s", b(25, 20)))
    W(ul_close())

    # Snapfire
    W(hero_header("Snapfire"))
    W(ability("Scatterblast"))
    W(ul_open())
    W(li("Cooldown decreased from 18/15/12/9s to 17/14/11/8s", b([18, 15, 12, 9], [17, 14, 11, 8], l=True)))
    W(li("Initial radius increased from 225 to 250", b(225, 250)))
    W(ul_close())

    # Spectre
    W(hero_header("Spectre"))
    W(ul_open())
    W(li("Strength gain decreased from 2.4 to 2.3", b(2.4, 2.3)))
    W(ul_close())
    W(ability("Dispersion"))
    W(ul_open())
    W(li("Max Radius decreased from 800 to 700", b(800, 700)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Spectral Dagger Cooldown Reduction decreased from 4s to 3s", b(4, 3, l=True)))
    W(ul_close())

    # Techies
    W(hero_header("Techies"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10 Talent Magic Resistance decreased from +20% to +15%", b(20, 15)))
    W(li("Level 15 Talent Blast Off! Damage decreased from +200 to +175", b(200, 175)))
    W(ul_close())

    # Terrorblade
    W(hero_header("Terrorblade"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20 Talent Conjure Image Duration decreased from +10s to +8s", b(10, 8)))
    W(ul_close())

    # Tidehunter
    W(hero_header("Tidehunter"))
    W(ul_open())
    W(li("Base Strength decreased from 26 to 25", b(26, 25)))
    W(li("Damage at level 1 decreased from 51-57 to 50-56", br(51, 57, 50, 56)))
    W(ul_close())
    W(ability("Leviathan's Catch"))
    W(ul_open())
    W(li("Now gains fish on every even level instead of every level", t("NERF")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15 Talent Gush Damage decreased from +100 to +90", b(100, 90)))
    W(li("Level 25 Talent Anchor Smash damage to buildings decreased from 100% to 50%", b(100, 50)))
    W(ul_close())

    # Timbersaw
    W(hero_header("Timbersaw"))
    W(ability("Whirling Death"))
    W(ul_open())
    W(li("Damage rescaled from 75/120/165/210 to 60/120/180/240", b([75, 120, 165, 210], [60, 120, 180, 240])))
    W(ul_close())
    W(ability("Timber Chain"))
    W(ul_open())
    W(li("Damage increased from 45/100/155/210 to 45/105/165/225", b([45, 100, 155, 210], [45, 105, 165, 225])))
    W(ul_close())
    W(ability("Chakram"))
    W(ul_open())
    W(li("Pass Damage rescaled from 100/150/200 to 75/150/225", b([100, 150, 200], [75, 150, 225])))
    W(ul_close())

    # Tinker
    W(hero_header("Tinker"))
    W(ability("Deploy Turrets"))
    W(ul_open())
    W(li("Missile speed increased from 1200 to 1350", b(1200, 1350)))
    W(li("Base activation time decreased from 0.3s to 0s", b(0.3, 0, l=True)))
    W(li("Aghanim's Scepter no longer makes activation faster", ""))
    W(ul_close())

    # Tiny
    W(hero_header("Tiny"))
    W(ul_open())
    W(li("Intelligence gain increased from 2.2 to 2.4", b(2.2, 2.4)))
    W(ul_close())
    W(ability("Tree Volley", slug="tiny_tree_channel"))
    W(ul_open())
    W(li("No longer applies cleave", t("DEL")))
    W(ul_close())

    # Treant Protector
    W(hero_header("Treant Protector"))
    W(ability("Nature's Grasp"))
    W(ul_open())
    W(li("Cooldown increased from 20/19/18/17s to 23/21/19/17s", b([20, 19, 18, 17], [23, 21, 19, 17], l=True)))
    W(ul_close())

    # Tusk
    W(hero_header("Tusk"))
    W(ability("Bitter Chill"))
    W(ul_open())
    W(li_formula("Attack Slow decreased", "17 + 3 per level", "12 + 3 per level", lambda L: 17.0 + 3.0*L, lambda L: 12.0 + 3.0*L))
    W(ul_close())
    W(ability("Drinking Buddies"))
    W(ul_open())
    W(li("No longer has an alt-cast", t("MISC")))
    W(li("Bonus Armor decreased from 10 to 7", b(10, 7)))
    W(ul_close())

    # Void Spirit
    W(hero_header("Void Spirit"))
    W(ability("Dissimilate"))
    W(ul_open())
    W(li("Damage decreased from 120/200/280/360 to 105/185/265/345", b([120, 200, 280, 360], [105, 185, 265, 345])))
    W(ul_close())

    # Windranger
    W(hero_header("Windranger"))
    W(ul_open())
    W(li("Base Health Regen increased by 0.5", bstat_h("Windranger", "StatusHealthRegen", "7.41b", 0.5), extra=note_box(hero="Windranger", field="StatusHealthRegen", before_patch="7.41b")))
    W(ul_close())
    W(ability("Powershot"))
    W(ul_open())
    W(li("Slow increased from 20/25/30/35% to 22/28/34/40%", b([20, 25, 30, 35], [22, 28, 34, 40])))
    W(ul_close())
    W(ability("Gale Force"))
    W(ul_open())
    W(li("Cooldown decreased from 30s to 25s", b(30, 25, l=True)))
    W(ul_close())

    write_footer()
    save_html('patches/7.41b.html')

