from patch.api import *

def build():
    write_head("7.41c", "06.05.2026")

    # 7.41c content is HANDCRAFTED — preserves manual corrections, formula tables,
    # wrong-line/wrong-word annotations and subnotes that auto-gen can't produce.
    # 7.41c content was originally raw HTML — converted to W() calls
    # via _convert_handcrafted.py. Special inline HTML preserved as W('''...''').
    W(section("General Updates"))
    W(plain_header("Mechanics"))
    W(ul_open())
    W(li("Units with flying vision no longer ignore vision restrictions of Roshan's pits. They can no longer see into them from outside and vice versa", t("NERF")))
    W(ul_close())
    W(subnote("Affects Clockwerk during Jetpack, Drow Ranger's Glacier, Monkey King during Tree Dance, Night Stalker during Dark Ascension, Treant Protector's Eyes in the Forest, and Visage's Familiars"))
    W(plain_header("Map Objectives"))
    W(subgroup("Tormentor"))
    W(ul_open())
    W(li("Alleviation: Max health regen increased from 2% to 2.25%", b(2, 2.25)))
    W(li("Alleviation: Duration increased from 10s to 15s", b(10, 15)))
    W(ul_close())
    W(section("Item Updates"))
    W(item_header("Bloodstone"))
    W(ul_open())
    W(li(
        '<span class="wrong-word">Health bonus increased from +600 to +625</span>',
        '<span class="badge-group" data-overall="buff"><span class="badge buff1">+4%</span></span>',
        extra=note_box('This change is wrongly stated. The real change is 650 → 625 <span class="badge-group" data-overall="nerf"><span class="badge nerf1">-4%</span></span>'),
        force_tag="nerf"
    ))
    W(li("Bloodpact cooldown increased from 30s to 35s", b(30, 35, l=True)))
    W(li("Spell Weakness Aura damage from spells taken decreased from 12% to 10%", b(12, 10)))
    W(ul_close())
    W(item_header("Boots of Bearing"))
    W(ul_open())
    W(li("Swiftness Aura allied movement speed decreased from 20 to 15", b(20, 15)))
    W(ul_close())
    W(item_header("Crella's Crozier"))
    W(ul_open())
    W(li("Rite of Rumusque movement speed steal increased from 5% to 6%", b(5, 6)))
    W(ul_close())
    W(item_header("Disperser"))
    W(ul_open())
    W(li("Suppress duration decreased from 5s to 4s", b(5, 4)))
    W(ul_close())
    W(item_header("Essence Distiller"))
    W(ul_open())
    W(li("Soul Release radius when ground targeted increased from 400 to 450", b(400, 450)))
    W(ul_close())
    W(item_header("Harpoon"))
    W(ul_open())
    W(li("Draw Forth can no longer move the Harpoon caster if they are rooted/leashed/bound", t("NERF")))
    W(ul_close())
    W(subnote("Still affects rooted/leashed/bound targets"))
    W(item_header("Heart of Tarrasque"))
    W(ul_open())
    W(li("Recipe cost increased from 600 to 700", b(600, 700, l=True)))
    W(li("Total cost increased from 5100g to 5200g", b(5100, 5200, l=True)))
    W(ul_close())
    W(item_header("Mage Slayer"))
    W(ul_open())
    W(li("Mage Slayer damage per second decreased from 40 to 35", b(40, 35)))
    W(ul_close())
    W(item_header("Silver Edge"))
    W(ul_open())
    W(li("Shadow Walk bonus movement speed decreased from 25% to 22%", b(25, 22)))
    W(li("Shadow Walk cooldown increased from 20s to 22s", b(20, 22, l=True)))
    W(ul_close())
    W(item_header("Shiva's Guard"))
    W(ul_open())
    W(li("Freezing Aura attack speed reduction decreased from 45 to 40", b(45, 40)))
    W(ul_close())
    W(item_header("Soul Ring"))
    W(ul_open())
    W(li("Cooldown increased from 25s to 30s", b(25, 30, l=True)))
    W(ul_close())
    W(item_header("Specialist's Array"))
    W(ul_open())
    W(li("Agility bonus increased from +12 to +15", b(12, 15)))
    W(ul_close())
    W(section("Neutral Item Updates"))
    W(enchant_header("Crude", "crude"))
    W(ul_open())
    W(li("Intelligence penalty increased from 6% to 9%", b(6, 9, l=True)))
    W(ul_close())
    W(enchant_header("Greedy", "greedy"))
    W(ul_open())
    W(li("Mana bonus decreased from 200/250 to 150/200", b([200, 250], [150, 200])))
    W(ul_close())
    W(enchant_header("Tough", "tough"))
    W(ul_open())
    W(li("Damage bonus decreased from +7/10/13/16 to +6/9/12/15", b([7, 10, 13, 16], [6, 9, 12, 15])))
    W(ul_close())
    W(section("Hero Updates"))
    W(hero_header("Abaddon"))
    W(ul_open())
    W(li("Base Intelligence increased by 1", bstat_h("Abaddon", "AttributeBaseIntelligence", "7.41b", 1), extra=note_box(hero="Abaddon", field="AttributeBaseIntelligence", before_patch="7.41b", extra_note="Damage at level 1 unchanged at 49-59")))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Curse of Avernus DPS increased from +25 to +30", b(25, 30)))
    W(ul_close())
    W(hero_header("Alchemist"))
    W(subgroup("Abilities"))
    W(ability("Greevil's Greed", slug="alchemist_goblins_greed"))
    W(ul_open())
    W(li("Bonus base/max Extra Gold per melted Scepter decreased from +6 to +3", b(6, 3)))
    W(ul_close())
    W(ability("Acid Spray"))
    W(ul_open())
    W(li("Cooldown rescaled from 22/21/20/19s to 21s", b([22, 21, 20, 19], 21, l=True)))
    W(ul_close())
    W(ability("Chemical Rage"))
    W(ul_open())
    W(li("Bonus Health Regen decreased from 60/90/120 to 50/85/120", b([60, 90, 120], [50, 85, 120])))
    W(ul_close())
    W(hero_header("Ancient Apparition"))
    W(subgroup("Abilities"))
    W(ability("Ice Blast"))
    W(ul_open())
    W(li("Path Radius increased from 275 to 300", b(275, 300)))
    W(li("Base Area of Effect Radius increased from 275 to 300", b(275, 300)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20: Chilling Touch Damage increased from +80 to +100", b(80, 100)))
    W(ul_close())
    W(hero_header("Anti-Mage"))
    W(subgroup("Abilities"))
    W(ability("Persecutor", slug="antimage_persectur"))
    W(ul_open())
    W(li("Minimum mana threshold for slow improved from 50% to 60%", b(50, 60)))
    W(ul_close())
    W(hero_header("Arc Warden"))
    W(ul_open())
    W(li("Base Agility increased from 20 to 22", b(20, 22)))
    W(li("Damage at level 1 increased from 51-57 to 52-58", br(51, 57, 52, 58)))
    W(ul_close())
    W(hero_header("Bane"))
    W(subgroup("Abilities"))
    W(ability("Brain Sap"))
    W(ul_open())
    W(li("Mana Cost decreased from 120/130/140/150 to 105/120/135/150", b([120, 130, 140, 150], [105, 120, 135, 150], l=True)))
    W(ul_close())
    W(hero_header("Batrider"))
    W(ul_open())
    W(li("Base Movement Speed decreased from 320 to 310", b(320, 310)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Sticky Napalm"))
    W(ul_open())
    W(li("Aghanim's Shard building damage decreased from 25% to 20%", b(25, 20)))
    W(ul_close())
    W(ability("Firefly"))
    W(ul_open())
    W(li("Damage per second decreased from 25/50/75/100 to 20/40/60/80", b([25, 50, 75, 100], [20, 40, 60, 80])))
    W(ul_close())
    W(ability("Flaming Lasso"))
    W(ul_open())
    W(li("Total Damage decreased from 200/350/500 to 125/250/375", b([200, 350, 500], [125, 250, 375])))
    W(ul_close())
    W(hero_header("Beastmaster"))
    W(ul_open())
    W(li("Base Strength decreased from 25 to 24", b(25, 24)))
    W(li("Damage at level 1 decreased from 50-54 to 49-53", br(50, 54, 49, 53)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Wild Axes"))
    W(ul_open())
    W(li("Mana Cost increased from 50/55/60/65 to 65", b([50, 55, 60, 65], 65, l=True)))
    W(ul_close())
    W(ability("Summon Razorback"))
    W(ul_open())
    W(li("Boar Attack Damage decreased from 30/45/60/75 to 24/41/58/75", b([30, 45, 60, 75], [24, 41, 58, 75])))
    W(ul_close())
    W(ability("Drums of Slom"))
    W(ul_open())
    W(li("Damage Radius decreased from 600 to 525", b(600, 525)))
    W(li("Drum Hit Damage decreased from 80 to 70", b(80, 70)))
    W(ul_close())
    W(hero_header("Bounty Hunter"))
    W(subgroup("Abilities"))
    W(ability("Shuriken Toss"))
    W(ul_open())
    W(li("Mana Cost increased from 75/80/85/90 to 75/85/95/105", b([75, 80, 85, 90], [75, 85, 95, 105], l=True)))
    W(ul_close())
    W(ability("Shadow Walk", slug="bounty_hunter_wind_walk"))
    W(ul_open())
    W(li("Bonus Speed increased from 8/12/16/20% to 11/14/17/20%", b([8, 12, 16, 20], [11, 14, 17, 20])))
    W(ul_close())
    W(ability("Track"))
    W(ul_open())
    W(li("Mana Cost decreased from 60 to 50", b(60, 50, l=True)))
    W(ul_close())
    W(hero_header("Brewmaster"))
    W(subgroup("Abilities"))
    W(ability("Primal Split"))
    W(ul_open())
    W(li("Cancel Split now has a 3s initial cooldown", '<span class="badge qol" data-tag="qol">QoL</span>'))
    W(ul_close())
    W(hero_header("Bristleback"))
    W(subgroup("Abilities"))
    W(ability("Warpath"))
    W(ul_open())
    W(li("Damage per stack decreased from 15/20/25 to 12/16/20", b([15, 20, 25], [12, 16, 20])))
    W(ul_close())
    W(ability("Hairball"))
    W(ul_open())
    W(li("Cooldown increased from 13s to 15s", b(13, 15, l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25: Bristleback Damage Threshold Reduction increased from 25 to 30", b(25, 30)))
    W(ul_close())
    W(hero_header("Broodmother"))
    W(subgroup("Abilities"))
    W(ability("Insatiable Hunger"))
    W(ul_open())
    W(li("Spiderling Radius increased from 800 to 1200", b(800, 1200)))
    W(ul_close())
    W(ability("Spinner's Snare", slug="broodmother_sticky_snare"))
    W(ul_open())
    W(li("Mana Cost decreased from 100 to 70", b(100, 70, l=True)))
    W(ul_close())
    W(hero_header("Centaur Warrunner"))
    W(ul_open())
    W(li("Base Strength increased from 27 to 28", b(27, 28)))
    W(li("Damage at level 1 increased from 63-65 to 64-66", br(63, 65, 64, 66)))
    W(li("Strength gain increased from 4.2 to 4.3", b(4.2, 4.3)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25: Hoof Stomp Duration increased from +0.8s to +1.0s", b(0.8, 1)))
    W(ul_close())
    W(hero_header("Chaos Knight"))
    W(subgroup("Abilities"))
    W(ability("Chaos Strike"))
    W(ul_open())
    W(li("Critical Max increased from 140/180/220/260% to 150/190/230/270%", b([140, 180, 220, 260], [150, 190, 230, 270])))
    W(ul_close())
    W(hero_header("Dark Seer"))
    W(ul_open())
    W(li("Base Intelligence increased from 22 to 23", b(22, 23)))
    W(li("Damage at level 1 increased from 53-59 to 54-60", br(53, 59, 54, 60)))
    W(ul_close())
    W(hero_header("Dark Willow"))
    W(subgroup("Abilities"))
    W(ability("Terrorize"))
    W(ul_open())
    W(li("Radius increased from 400/450/500 to 450/500/550", b([400, 450, 500], [450, 500, 550])))
    W(ul_close())
    W(hero_header("Dawnbreaker"))
    W(ul_open())
    W(li("Base Damage decreased by 1", bstat_h("Dawnbreaker", "AttackDamageMin", "7.41b", -1), extra=note_box(hero="Dawnbreaker", field="AttackDamageMin", before_patch="7.41b")))
    W(li("Damage at level 1 decreased from 56-60 to 55-59", br(56, 60, 55, 59)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Solar Guardian"))
    W(ul_open())
    W(li("Landing Stun Duration decreased from 1.4/1.6/1.8s to 1.2/1.4/1.6s", b([1.4, 1.6, 1.8], [1.2, 1.4, 1.6])))
    W(ul_close())
    W(hero_header("Doom"))
    W(subgroup("Abilities"))
    W(ability("Scorched Earth"))
    W(ul_open())
    W(li("Bonus HP Regen decreased from 7/8/9/10 to 6.66", b([7, 8, 9, 10], 6.66)))
    W(ul_close())
    W(hero_header("Drow Ranger"))
    W(subgroup("Abilities"))
    W(ability("Frost Arrows"))
    W(ul_open())
    W(li("Bonus Damage increased from 10/15/20/25 to 12/18/24/30", b([10, 15, 20, 25], [12, 18, 24, 30])))
    W(ul_close())
    W(ability("Gust", slug="drow_ranger_wave_of_silence"))
    W(ul_open())
    W(li("Mana Cost decreased from 70 to 55", b(70, 55, l=True)))
    W(ul_close())
    W(hero_header("Earth Spirit"))
    W(ul_open())
    W(li("Base Strength increased from 22 to 23", b(22, 23)))
    W(li("Damage at level 1 increased from 47-51 to 48-52", br(47, 51, 48, 52)))
    W(ul_close())
    W(hero_header("Elder Titan"))
    W(subgroup("Abilities"))
    W(ability("Echo Stomp"))
    W(ul_open())
    W(li("Damage increased from 60/100/140/180 to 65/110/155/200", b([60, 100, 140, 180], [65, 110, 155, 200])))
    W(li("Aghanim's Shard with alt-cast no longer swaps the position if Elder Titan is rooted", t("NERF")))
    W(ul_close())
    W(hero_header("Ember Spirit"))
    W(ul_open())
    W(li("Base Strength decreased from 22 to 21", b(22, 21)))
    W(ul_close())
    W(hero_header("Faceless Void"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20: Time Walk Cooldown Reduction decreased from 1.25s to 1s", b(1.25, 1)))
    W(li("Level 20: Attack Speed during Chronosphere decreased from +100 to +80", b(100, 80)))
    W(ul_close())
    W(hero_header("Gyrocopter"))
    W(subgroup("Abilities"))
    W(ability("Afterburner"))
    W(ul_open())
    W(li("Duration increased from 4s to 5s", b(4, 5)))
    W(ul_close())
    W(hero_header("Hoodwink"))
    W(ul_open())
    W(li("Base Damage increased by 3", t("MISC") + bstat_h("Hoodwink", "AttackDamageMin", "7.41b", 3), extra=note_box(hero="Hoodwink", field="AttackDamageMin", before_patch="7.41b", extra_note="Damage at level 1 unchanged at 47-54")))
    W(li("Base Agility decreased from 25 to 22", b(25, 22)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Sharpshooter"))
    W(ul_open())
    W(li("Knockback to Hoodwink won't be applied if Hoodwink is rooted", t("NERF")))
    W(ul_close())
    W(hero_header("Huskar"))
    W(ul_open())
    W(li("Base Health Regen decreased by 0.25", t("NERF")))
    W(ul_close())
    W(hero_header("Invoker"))
    W(ul_open())
    W(li("Base Movement Speed decreased from 285 to 280", b(285, 280)))
    W(ul_close())
    W(hero_header("Io"))
    W(subgroup("Abilities"))
    W(ability("Tether"))
    W(ul_open())
    W(li("HP/Mana Transfer decreased from 60/80/100/120% to 55/75/95/115%", b([60, 80, 100, 120], [55, 75, 95, 115])))
    W(ul_close())
    W(ability("Spirits"))
    W(ul_open())
    W(li("Now remembers the radius of the spirits between casts", '<span class="badge qol" data-tag="qol">QoL</span>'))
    W(ul_close())
    W(hero_header("Jakiro"))
    W(ul_open())
    W(li("Strength gain increased from 2.5 to 2.6", b(2.5, 2.6)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Macropyre"))
    W(ul_open())
    W(li("Mana Cost decreased from 250/350/450 to 225/325/425", b([250, 350, 450], [225, 325, 425], l=True)))
    W(ul_close())
    W(hero_header("Juggernaut"))
    W(subgroup("Abilities"))
    W(ability("Blade Fury"))
    W(ul_open())
    W(li("Damage per second increased from 80/110/140/170 to 85/115/145/175", b([80, 110, 140, 170], [85, 115, 145, 175])))
    W(ul_close())
    W(hero_header("Keeper of the Light"))
    W(ul_open())
    W(li("Base Movement Speed decreased from 315 to 310", b(315, 310)))
    W(ul_close())
    W(hero_header("Kunkka"))
    W(subgroup("Abilities"))
    W(ability("Admiral's Rum"))
    W(ul_open())
    W(li_formula("Cooldown decreased",
                 "60.5s − 0.5s per level", "50.5s − 0.5s per level",
                 lambda L: 60.5 - 0.5 * L, lambda L: 50.5 - 0.5 * L, l=True,
                 value_fmt="{:g}s"))
    W(ul_close())
    W(hero_header("Largo"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20: +200 Catchy Lick Damage replaced with 2× Catchy Lick Charges", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(li("Level 25: 2× Catchy Lick Charges replaced with 2× Frogstomp Stomps / Interval", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(ul_close())
    W(hero_header("Lich"))
    W(subgroup("Abilities"))
    W(ability("Sinister Gaze"))
    W(ul_open())
    W(li("Mana Drain per second increased from 20% to 25%", b(20, 25)))
    W(ul_close())
    W(hero_header("Lina"))
    W(subgroup("Abilities"))
    W(ability("Light Strike Array"))
    W(ul_open())
    W(li("Damage increased from 80/120/160/200 to 80/125/170/215", b([80, 120, 160, 200], [80, 125, 170, 215])))
    W(ul_close())
    W(ability("Laguna Blade"))
    W(ul_open())
    W(li("Damage increased from 380/565/750 to 400/580/760", b([380, 565, 750], [400, 580, 760])))
    W(ul_close())
    W(hero_header("Lone Druid"))
    W(subgroup("Abilities"))
    W(ability("Summon Spirit Bear", slug="lone_druid_spirit_bear"))
    W(ul_open())
    W(li("Mana Cost increased from 75 to 100", b(75, 100, l=True)))
    W(ul_close())
    W(ability("Spirit Link"))
    W(ul_open())
    W(li("Shared Lifesteal now follows general lifesteal rules and has a creep penalty of 40%", t("NERF"),
         extra=inline_note("Previously creeps used a 100% lifesteal multiplier; now follows the global creep-lifesteal value — " + b(100, 60))))
    W(ul_close())
    W(ability("Savage Roar"))
    W(ul_open())
    W(li("Aghanim's Shard buff duration decreased from 5s to 4s", b(5, 4)))
    W(ul_close())
    W(ul_open())
    W(li("Aghanim's Shard bonus movement speed decreased from 15% to 10%", b(15, 10)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: −25s Summon Spirit Bear Cooldown replaced with +5s True Form Duration", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(ul_close())
    W(unit_header("Spirit Bear", "../icons/abilities/lone_druid_spirit_bear.png", kind="Creep-hero"))
    W(ul_open())
    W(li_formula("Gold/Experience Bounty changed",
                 "175 + 8 per Spirit Bear level", "165 + 10 per Spirit Bear level",
                 lambda L: 175 + 8 * L,
                 lambda L: 165 + 10 * L,
                 levels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25, 30],
                 l=True,
                 rework_badge=False))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25: Demolish Bonus Building Damage decreased from +20% to +15%", b(20, 15)))
    W(ul_close())
    W(hero_header("Lycan"))
    W(subgroup("Abilities"))
    W(ability("Feral Impulse"))
    W(ul_open())
    W(li("Health Regen increased from 1/3/5/7 to 2/4/6/8", b([1, 3, 5, 7], [2, 4, 6, 8])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Wolves Damage increased from +10 to +14", b(10, 14)))
    W(li("Level 15: Summon Wolves Health increased from +350 to +375", b(350, 375)))
    W(ul_close())
    W(hero_header("Magnus"))
    W(subgroup("Abilities"))
    W(ability("Shockwave"))
    W(ul_open())
    W(li("Slow Duration increased from 0.4/0.6/0.8/1.0s to 0.55/0.7/0.85/1.0s", b([0.4, 0.6, 0.8, 1], [0.55, 0.7, 0.85, 1])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: All Attributes per hero hit with Reverse Polarity increased from +12 to +14", b(12, 14)))
    W(ul_close())
    W(hero_header("Marci"))
    W(subgroup("Abilities"))
    W(ability("Bodyguard"))
    W(ul_open())
    W(li("Cast Range increased from 500 to 600", b(500, 600)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: Dispose Damage increased from +100 to +115", b(100, 115)))
    W(ul_close())
    W(hero_header("Mars"))
    W(subgroup("Abilities"))
    W(ability("Dauntless"))
    W(ul_open())
    W(li("HP Regen per extra enemy increased from 40% to 50%", b(40, 50)))
    W(ul_close())
    W(ability("Spear of Mars", slug="mars_spear"))
    W(ul_open())
    W(li("Mana Cost decreased from 100/110/120/130 to 90/100/110/120", b([100, 110, 120, 130], [90, 100, 110, 120], l=True)))
    W(ul_close())
    W(hero_header("Mirana"))
    W(subgroup("Abilities"))
    W(ability("Sacred Arrow", slug="mirana_arrow"))
    W(ul_open())
    W(li("Damage increased from 60/150/240/330 to 60/160/260/360", b([60, 150, 240, 330], [60, 160, 260, 360])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: Leap Attack Speed increased from +90 to +100", b(90, 100)))
    W(li("Level 20: Celestial Quiver Damage increased from +40 to +50", b(40, 50)))
    W(ul_close())
    W(hero_header("Monkey King"))
    W(ul_open())
    W(li("Base Agility decreased from 24 to 23", b(24, 23)))
    W(li("Damage at level 1 decreased from 53-57 to 52-56", br(53, 57, 52, 56)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Primal Spring"))
    W(ul_open())
    W(li("Movement Slow decreased from 35/50/65/80% to 30/40/50/60%", b([35, 50, 65, 80], [30, 40, 50, 60])))
    W(ul_close())
    W(hero_header("Morphling"))
    W(subgroup("Abilities"))
    W(ability("Waveform"))
    W(ul_open())
    W(li("Will now be cast in the desired direction, if the target location is further than the cast range", '<span class="badge qol" data-tag="qol">QoL</span>'))
    W(ul_close())
    W(hero_header("Muerta"))
    W(ul_open())
    W(li("Base Attack Speed decreased from 115 to 110", b(115, 110)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Supernatural"))
    W(ul_open())
    W(li_formula("Maximum Stack Count increased",
                 "1 per hero level",
                 "5 + 1 per hero level",
                 lambda L: 1 * L,
                 lambda L: 5 + 1 * L,
                 rework_badge=False))
    W(ul_close())
    W(hero_header("Nature's Prophet"))
    W(subgroup("Abilities"))
    W(ability("Nature's Call", slug="furion_force_of_nature"))
    W(ul_open())
    W(li("Mana Cost decreased from 100 to 85/90/95/100", b(100, [85, 90, 95, 100], l=True)))
    W(li("Treant Bonus Hero Damage increased from 4/8/12/16 to 6/10/14/18", b([4, 8, 12, 16], [6, 10, 14, 18])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20: Sprout Damage increased from +170 to +220", b(170, 220)))
    W(li("Level 20: Wrath of Nature Cooldown Reduction increased from 15s to 20s", b(15, 20)))
    W(ul_close())
    W(hero_header("Ogre Magi"))
    W(ul_open())
    W(li("Strength gain decreased from 4.2 to 4.0", b(4.2, 4)))
    W(ul_close())
    W(hero_header("Omniknight"))
    W(subgroup("Abilities"))
    W(ability("Repel", slug="omniknight_martyr"))
    W(ul_open())
    W(li("Cooldown decreased from 40/36/32/28s to 40/35/30/25s", b([40, 36, 32, 28], [40, 35, 30, 25], l=True)))
    W(ul_close())
    W(ability("Hammer of Purity"))
    W(ul_open())
    W(li("Damage increased from 20/40/60/80 to 25/45/65/85", b([20, 40, 60, 80], [25, 45, 65, 85])))
    W(ul_close())
    W(hero_header("Outworld Destroyer"))
    W(subgroup("Abilities"))
    W(ability("Objurgation"))
    W(ul_open())
    W(li("Mana Cost decreased from 250 to 175", b(250, 175, l=True)))
    W(ul_close())
    W(ability("Sanity's Eclipse", slug="obsidian_destroyer_sanity_eclipse"))
    W(ul_open())
    W(li("Radius increased from 450/500/550 to 500/525/550", b([450, 500, 550], [500, 525, 550])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 20: Astral Imprisonment Mana Capacity Steal increased from 10% to 12%", b(10, 12)))
    W(ul_close())
    W(hero_header("Pangolier"))
    W(ul_open())
    W(li("Base Health Regen decreased by 1.0", bstat_h("Pangolier", "StatusHealthRegen", "7.41b", -1), extra=note_box(hero="Pangolier", field="StatusHealthRegen", before_patch="7.41b")))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Swashbuckle"))
    W(ul_open())
    W(li("Mana Cost increased from 75/80/85/90 to 85/90/95/100", b([75, 80, 85, 90], [85, 90, 95, 100], l=True)))
    W(ul_close())
    W(ability("Roll Up", slug="pangolier_rollup"))
    W(ul_open())
    W(li("Mana Cost increased from 50 to 75", b(50, 75, l=True)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Lucky Shot Armor Reduction decreased from +3 to +2", b(3, 2)))
    W(ul_close())
    W(hero_header("Phantom Assassin"))
    W(ul_open())
    W(li("Base Agility increased from 21 to 22", b(21, 22)))
    W(li("Damage at level 1 increased from 56-58 to 57-59", br(56, 58, 57, 59)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Phantom Strike Duration increased from +0.6 to +0.8s", b(0.6, 0.8)))
    W(ul_close())
    W(hero_header("Phantom Lancer"))
    W(subgroup("Abilities"))
    W(ability("Phantom Rush", slug="phantom_lancer_phantom_edge"))
    W(ul_open())
    W(li("Aghanim's Scepter bonus max rush distance decreased from +625 to +575", b(625, 575),
         extra=inline_note("Effective max rush distance per Phantom Rush level: 1225/1300/1375/1450 → 1175/1250/1325/1400.")))
    W(ul_close())
    W(hero_header("Phoenix"))
    W(subgroup("Abilities"))
    W(ability("Dying Light"))
    W(ul_open())
    W(li("Missing Health as Damage decreased from 4% to 3.5%", b(4, 3.5)))
    W(ul_close())
    W(ability("Sun Ray"))
    W(ul_open())
    W(li("Max Health as Heal per second decreased from 0.5/1/1.5/2% to 0.4/0.8/1.2/1.6%", b([0.5, 1, 1.5, 2], [0.4, 0.8, 1.2, 1.6])))
    W(ul_close())
    W(ability("Supernova"))
    W(ul_open())
    W(li("Damage per second decreased from 60/90/120 to 50/80/110", b([60, 90, 120], [50, 80, 110])))
    W(ul_close())
    W(hero_header("Primal Beast"))
    W(subgroup("Abilities"))
    W(ability("Trample"))
    W(ul_open())
    W(li("Damage AoE decreased from 230 to 200", b(230, 200)))
    W(ul_close())
    W(hero_header("Puck"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: −15s Dream Coil Cooldown replaced with +2% Puckish Health and Mana Restoration", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(li("Level 25: Dream Coil Pierces Debuff Immunity replaced with −30s Dream Coil Cooldown", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(ul_close())
    W(hero_header("Queen of Pain"))
    W(ul_open())
    W(li("Base Agility decreased from 22 to 20", b(22, 20)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Shadow Strike"))
    W(ul_open())
    W(li("Cooldown rescaled from 13/10/7/4s to 11/9/7/5s", b([13, 10, 7, 4], [11, 9, 7, 5], l=True)))
    W(li("Aghanim's Scepter AoE decreased from 375 to 300", b(375, 300)))
    W(ul_close())
    W(hero_header("Razor"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: Static Link Damage Steal increased from +5 to +6", b(5, 6)))
    W(li("Level 20: Storm Surge Slow and Damage increased from +30% to +35%", b(30, 35)))
    W(ul_close())
    W(hero_header("Rubick"))
    W(ul_open())
    W(li("Agility gain decreased from 2.5 to 2.2", b(2.5, 2.2)))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: Fade Bolt Cooldown Reduction increased from 3s to 4s", b(3, 4)))
    W(li("Level 15: Stolen Spells Mana Cost Reduction decreased from 50% to 40%", b(50, 40)))
    W(li("Level 25: Curiosity Bonuses decreased from 2× to 1.5×", b(2, 1.5)))
    W(ul_close())
    W(hero_header("Sand King"))
    W(ul_open())
    W(li("Base Attack Speed decreased from 110 to 100", b(110, 100)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Stinger", slug="sandking_scorpion_strike"))
    W(ul_open())
    W(li("Slow Duration rescaled from 4/5/6/7s to 5s", b([4, 5, 6, 7], 5)))
    W(ul_close())
    W(ability("Epicenter", slug="sandking_epicenter"))
    W(ul_open())
    W(li("Base Radius decreased from 500 to 450", b(500, 450)))
    W(ul_close())
    W(hero_header("Shadow Fiend"))
    W(subgroup("Abilities"))
    W(ability("Shadowraze", slug="nevermore_shadowraze1"))
    W(ul_open())
    W(li("Mana Cost decreased from 80 to 75", b(80, 75, l=True)))
    W(ul_close())
    W(ability("Presence of the Dark Lord", slug="nevermore_dark_lord"))
    W(ul_open())
    W(li("Armor Reduction rescaled from 3/4/5/6 to 2.5/4/5.5/7", b([3, 4, 5, 6], [2.5, 4, 5.5, 7])))
    W(ul_close())
    W(hero_header("Skywrath Mage"))
    W(subgroup("Abilities"))
    W(ability("Mystic Flare"))
    W(ul_open())
    W(li("Cooldown decreased from 60/40/20s to 55/35/15s", b([60, 40, 20], [55, 35, 15], l=True)))
    W(ul_close())
    W(hero_header("Slardar"))
    W(subgroup("Abilities"))
    W(ability("Slithereen Crush"))
    W(ul_open())
    W(li("Cooldown increased from 7s to 8.5/8/7.5/7s", b(7, [8.5, 8, 7.5, 7], l=True)))
    W(ul_close())
    W(hero_header("Snapfire"))
    W(ul_open())
    W(li("Base Damage increased by 2", bstat_h("Snapfire", "AttackDamageMin", "7.41b", 2), extra=note_box(hero="Snapfire", field="AttackDamageMin", before_patch="7.41b")))
    W(li("Damage at level 1 increased from 51-57 to 53-59", br(51, 57, 53, 59)))
    W(ul_close())
    W(hero_header("Spectre"))
    W(ul_open())
    W(li("Base Agility increased from 26 to 29", b(26, 29)))
    W(li("Damage at level 1 increased from 49-53 to 52-56", br(49, 53, 52, 56)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Dispersion"))
    W(ul_open())
    W(li("Damage rescaled from 8/12/16/20% to 9/12/15/18%", b([8, 12, 16, 20], [9, 12, 15, 18])))
    W(ul_close())
    W(hero_header("Storm Spirit"))
    W(subgroup("Abilities"))
    W(ability("Galvanized"))
    W(ul_open())
    W(li('Now gains a charge every 3 levels', '<span class="badge new" data-tag="new" data-overall="buff">NEW</span>'))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Overload Attack/Movement Speed Slow increased from +20/20% to +25/25%", b([20, 20], [25, 25])))
    W(ul_close())
    W(hero_header("Sven"))
    W(subgroup("Abilities"))
    W(ability("Storm Hammer", slug="sven_storm_bolt"))
    W(ul_open())
    W(li("Mana Cost decreased from 110/115/120/125 to 110", b([110, 115, 120, 125], 110, l=True)))
    W(ul_close())
    W(hero_header("Techies"))
    W(ul_open())
    W(li("Base Mana Regen decreased by 0.5", bstat_h("Techies", "StatusManaRegen", "7.41b", -0.5), extra=note_box(hero="Techies", field="StatusManaRegen", before_patch="7.41b")))
    W(li("Intelligence gain decreased from 3.0 to 2.7", b(3, 2.7)))
    W(li("Damage gain per level decreased from 3.3 to 3.2 as a result", b(3.3, 3.2)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("M.A.D.", slug="techies_mutually_assured_destruction"))
    W(ul_open())
    W(li_formula("Mana Pool as Regen rescaled",
                 "0.08% + 0.02% per level", "0.1% + 0.01% per level",
                 lambda L: 0.08 + 0.02 * L, lambda L: 0.1 + 0.01 * L,
                 value_fmt="{:.2f}%"))
    W(ul_close())
    W(ability("Reactive Tazer"))
    W(ul_open())
    W(li("Explosion Radius decreased from 450 to 400", b(450, 400)))
    W(ul_close())
    W(hero_header("Templar Assassin"))
    W(ul_open())
    W(li("Base Movement Speed increased from 310 to 315", b(310, 315)))
    W(ul_close())
    W(hero_header("Tidehunter"))
    W(ul_open())
    W(li("Base Mana Regen decreased by 0.5", bstat_h("Tidehunter", "StatusManaRegen", "7.41b", -0.5), extra=note_box(hero="Tidehunter", field="StatusManaRegen", before_patch="7.41b")))
    W(ul_close())
    W(hero_header("Timbersaw"))
    W(ul_open())
    W(li("Base Damage increased by 2", bstat_h("Timbersaw", "AttackDamageMin", "7.41b", 2), extra=note_box(hero="Timbersaw", field="AttackDamageMin", before_patch="7.41b")))
    W(li(
        'Damage at level 1 <span class="wrong-word">decreased</span> from 46-50 to 48-52',
        '<span class="badge-group" data-overall="buff"><span class="badge buff1">+4%</span></span>',
        extra=note_box('The patch text says "decreased", but the values actually went up.'),
        force_tag="buff"
    ))
    W(li("Base Intelligence increased from 23 to 24", b(23, 24)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Reactive Armor"))
    W(ul_open())
    W(li("Bonus HP Regen increased from 0.4/0.5/0.6/0.7 to 0.5/0.6/0.7/0.8", b([0.4, 0.5, 0.6, 0.7], [0.5, 0.6, 0.7, 0.8])))
    W(ul_close())
    W(hero_header("Tinker"))
    W(subgroup("Abilities"))
    W(ability("Deploy Turrets"))
    W(ul_open())
    W(li("Updated sound effects", '<span class="badge misc" data-tag="misc">MISC</span>'))
    W(ul_close())
    W(hero_header("Tiny"))
    W(ul_open())
    W(li("Base Attack Speed decreased from 90 to 85", b(90, 85)))
    W(ul_close())
    W(subgroup("Abilities"))
    W(ability("Grow"))
    W(ul_open())
    W(li("Toss Bonus Damage increased from 50/175/300 to 50/200/350", b([50, 175, 300], [50, 200, 350])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: +8 Strength replaced with +2 Tree Grab Attacks", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(li("Level 15: −8% Grow Attack Speed Reduction replaced with +10 Strength", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(ul_close())
    W(hero_header("Treant Protector"))
    W(subgroup("Abilities"))
    W(ability("Eyes In The Forest"))
    W(ul_open())
    W(li("Added AoE indicator to cast", '<span class="badge qol" data-tag="qol">QoL</span>'))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Living Armor Heal Per Second decreased from +4 to +3", b(4, 3)))
    W(ul_close())
    W(hero_header("Troll Warlord"))
    W(subgroup("Abilities"))
    W(ability("Whirling Axes (Ranged)"))
    W(ul_open())
    W(li("Mana Cost decreased from 60 to 50", b(60, 50, l=True)))
    W(ul_close())
    W(ability("Whirling Axes (Melee)"))
    W(ul_open())
    W(li("Damage increased from 50/100/150/200 to 75/120/165/210", b([50, 100, 150, 200], [75, 120, 165, 210])))
    W(ul_close())
    W(hero_header("Tusk"))
    W(subgroup("Abilities"))
    W(ability("Drinking Buddies"))
    W(ul_open())
    W(li("No longer castable while rooted", t("DEL")))
    W(ul_close())
    W(hero_header("Vengeful Spirit"))
    W(subgroup("Abilities"))
    W(ability("Vengeance Aura", slug="vengefulspirit_command_aura"))
    W(ul_open())
    W(li("Self Bonus increased from 20% to 25%", b(20, 25)))
    W(ul_close())
    W(hero_header("Venomancer"))
    W(subgroup("Abilities"))
    W(ability("Poison Sting"))
    W(ul_open())
    W(li("Movement Slow decreased from 10% to 8%", b(10, 8)))
    W(ul_close())
    W(ability("Snakebite"))
    W(ul_open())
    W(li("Damage per second rescaled from 20/25/30/35 to 10/20/30/40", b([20, 25, 30, 35], [10, 20, 30, 40])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 15: Poison Sting Slow increased from +7% to +10%", b(7, 10)))
    W(li("Level 20: +40% Snakebite Damage replaced with +100 Snakebite Initial Damage", '<span class="badge rework" data-tag="rework">REWORK</span>'))
    W(ul_close())
    W(hero_header("Viper"))
    W(subgroup("Abilities"))
    W(ability("Nosedive", slug="viper_nose_dive"))
    W(ul_open())
    W(li("Cooldown increased from 20s to 25s", b(20, 25, l=True)))
    W(ul_close())
    W(hero_header("Weaver"))
    W(subgroup("Abilities"))
    W(ability("The Swarm"))
    W(ul_open())
    W(li("Mana Cost decreased from 110 to 110/105/100/95", b(110, [110, 105, 100, 95], l=True)))
    W(ul_close())
    W(hero_header("Windranger"))
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 25: Focus Fire Cooldown Advance on Kills decreased from 18s to 16s", b(18, 16)))
    W(li("Level 25: Powershot Max HP Execution Threshold increased from 15% to 16%", b(15, 16)))
    W(ul_close())
    W(hero_header("Winter Wyvern"))
    W(subgroup("Abilities"))
    W(ability("Splinter Blast"))
    W(ul_open())
    W(li("Movement Slow decreased from 28/32/36/40% to 27/30/33/36%", b([28, 32, 36, 40], [27, 30, 33, 36])))
    W(ul_close())
    W(subgroup("Talents"))
    W(ul_open())
    W(li("Level 10: Cold Embrace Base Heal per Second decreased from +20 to +15", b(20, 15)))
    W(ul_close())
    W(hero_header("Witch Doctor"))
    W(subgroup("Abilities"))
    W(ability("Voodoo Restoration"))
    W(ul_open())
    W(li("Radius increased from 500/550/600/650 to 650", b([500, 550, 600, 650], 650)))
    W(ul_close())


    write_footer()
    save_html('patches/7.41c.html')

